// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package server

import (
	"context"

	"flash-mall/app/product/rpc/internal/logic"
	"flash-mall/app/product/rpc/internal/svc"
	"flash-mall/app/product/rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) GetProductCard(ctx context.Context, in *product.GetProductCardReq) (*product.GetProductCardResp, error) {
	l := logic.NewGetProductCardLogic(ctx, s.svcCtx)
	return l.GetProductCard(in)
}

// 批量查询商品
func (s *ProductServer) ListProducts(ctx context.Context, in *product.ListProductsReq) (*product.ListProductsResp, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

// 扣减库存（正向操作）
func (s *ProductServer) Deduct(ctx context.Context, in *product.DeductReq) (*product.Empty, error) {
	l := logic.NewDeductLogic(ctx, s.svcCtx)
	return l.Deduct(in)
}

// 回滚库存（补偿操作，用于事务失败）
func (s *ProductServer) DeductRollback(ctx context.Context, in *product.DeductReq) (*product.Empty, error) {
	l := logic.NewDeductRollbackLogic(ctx, s.svcCtx)
	return l.DeductRollback(in)
}

// 归还库存
func (s *ProductServer) RevertStock(ctx context.Context, in *product.RevertStockReq) (*product.RevertStockResp, error) {
	l := logic.NewRevertStockLogic(ctx, s.svcCtx)
	return l.RevertStock(in)
}
