// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateOrderReq struct {
	// CHG 2026-02-07: 变更=新增 request_id; 之前=无幂等键; 原因=重复请求返回同一订单避免双下单。
	RequestId        string `json:"request_id"`
	UserId           int64  `json:"user_id"`
	ProductId        int64  `json:"product_id"`
	Amount           int64  `json:"amount"` // 购买数量
	ExpectedPriceFen int64  `json:"expected_price_fen,optional"`
}

type CreateOrderResp struct {
	OrderId          string `json:"order_id"`
	Status           string `json:"status"`
	PayableAmountFen int64  `json:"payable_amount_fen"`
	PaymentOrderId   string `json:"payment_order_id"`
}

type PayOrderReq struct {
	OrderId        string `json:"order_id"`
	PaymentOrderId string `json:"payment_order_id,optional"`
	OutTradeNo     string `json:"out_trade_no,optional"`
	PaidAmountFen  int64  `json:"paid_amount_fen,optional"`
	Provider       string `json:"provider,optional"`
	EventId        string `json:"event_id,optional"`
	Timestamp      string `json:"timestamp,optional"`
	Nonce          string `json:"nonce,optional"`
	Signature      string `json:"signature,optional"`
}

type PayOrderResp struct {
	OrderId string `json:"order_id"`
	Status  string `json:"status"`
}

type CancelOrderReq struct {
	OrderId string `json:"order_id"`
	Reason  string `json:"reason,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type CancelOrderResp struct {
	OrderId string `json:"order_id"`
	Status  string `json:"status"`
}

type ShipOrderReq struct {
	OrderId string `json:"order_id"`
}

type ShipOrderResp struct {
	OrderId string `json:"order_id"`
	Status  string `json:"status"`
}

type ConfirmReceiptReq struct {
	OrderId string `json:"order_id"`
}

type ConfirmReceiptResp struct {
	OrderId string `json:"order_id"`
	Status  string `json:"status"`
}

type RefundOrderReq struct {
	OrderId string `json:"order_id"`
	Reason  string `json:"reason,optional"`
}

type RefundOrderResp struct {
	OrderId string `json:"order_id"`
	Status  string `json:"status"`
}

type RefundApplyReq struct {
	OrderId string `json:"order_id"`
	Reason  string `json:"reason,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type RefundApplyResp struct {
	RefundId string `json:"refund_id"`
	OrderId  string `json:"order_id"`
	Status   string `json:"status"`
}

type OrderListItem struct {
	OrderId          string `json:"order_id"`
	ProductId        int64  `json:"product_id"`
	ProductName      string `json:"product_name"`
	Amount           int64  `json:"amount"`
	Status           int64  `json:"status"`
	StatusText       string `json:"status_text"`
	PayableAmountFen int64  `json:"payable_amount_fen"`
	CreateTime       string `json:"create_time"`
}

type OrderListResp struct {
	Items []OrderListItem `json:"items"`
}

type OrderDetailResp struct {
	OrderId            string `json:"order_id"`
	UserId             int64  `json:"user_id"`
	ProductId          int64  `json:"product_id"`
	ProductName        string `json:"product_name"`
	Amount             int64  `json:"amount"`
	Status             int64  `json:"status"`
	StatusText         string `json:"status_text"`
	OriginUnitPriceFen int64  `json:"origin_unit_price_fen"`
	SaleUnitPriceFen   int64  `json:"sale_unit_price_fen"`
	PayableAmountFen   int64  `json:"payable_amount_fen"`
	DiscountAmountFen  int64  `json:"discount_amount_fen"`
	PromotionType      string `json:"promotion_type"`
	PromotionTag       string `json:"promotion_tag"`
	PaymentOrderId     string `json:"payment_order_id"`
	PaymentStatus      int64  `json:"payment_status"`
	PaymentStatusText  string `json:"payment_status_text"`
	CreateTime         string `json:"create_time"`
}

type ProductCard struct {
	ProductId      int64  `json:"product_id"`
	Name           string `json:"name"`
	ImageUrl       string `json:"image_url"`
	OriginPriceFen int64  `json:"origin_price_fen"`
	FinalPriceFen  int64  `json:"final_price_fen"`
	PromotionTag   string `json:"promotion_tag"`
	StockAvailable int64  `json:"stock_available"`
}

type OrderStatusPollReq struct {
	RequestId string `form:"request_id"`
}

type OrderStatusPollResp struct {
	RequestId string `json:"request_id"`
	OrderId   string `json:"order_id,omitempty"`
	Status    string `json:"status"`
}

type DependencyStatus struct {
	Name   string `json:"name"`
	Ok     bool   `json:"ok"`
	Detail string `json:"detail"`
}

type SystemHealthResp struct {
	Overall      bool               `json:"overall"`
	Version      string             `json:"version"`
	Uptime       string             `json:"uptime"`
	Goroutines   int                `json:"goroutines"`
	ServerTime   int64              `json:"server_time"`
	Dependencies []DependencyStatus `json:"dependencies"`
}

// Admin API types
type AdminOrderListReq struct {
	Page        int64  `form:"page,optional,default=1"`
	PageSize    int64  `form:"page_size,optional,default=20"`
	ProductId   int64  `form:"product_id,optional"`
	SupplierId  int64  `form:"supplier_id,optional"`
	Status      int64  `form:"status,optional,default=-1"`
	UserId      int64  `form:"user_id,optional"`
	ProductName string `form:"product_name,optional"`
	CreatedFrom string `form:"created_from,optional"`
	CreatedTo   string `form:"created_to,optional"`
	OrderId     string `form:"order_id,optional"`
}

type AdminOrderListItem struct {
	OrderId          string `json:"order_id"`
	UserId           int64  `json:"user_id"`
	ProductId        int64  `json:"product_id"`
	ProductName      string `json:"product_name"`
	Amount           int64  `json:"amount"`
	Status           int64  `json:"status"`
	StatusText       string `json:"status_text"`
	PayableAmountFen int64  `json:"payable_amount_fen"`
	CreateTime       string `json:"create_time"`
}

type AdminOrderListResp struct {
	Items []AdminOrderListItem `json:"items"`
	Total int64                `json:"total"`
}

type AdminOrderStatusLogReq struct {
	OrderId string `form:"order_id"`
}

type AdminOrderStatusLogItem struct {
	Id             int64  `json:"id"`
	OrderId        string `json:"order_id"`
	FromStatus     int64  `json:"from_status"`
	FromStatusText string `json:"from_status_text"`
	ToStatus       int64  `json:"to_status"`
	ToStatusText   string `json:"to_status_text"`
	OperatorId     int64  `json:"operator_id"`
	Remark         string `json:"remark"`
	CreateTime     string `json:"create_time"`
}

type AdminOrderStatusLogResp struct {
	Items []AdminOrderStatusLogItem `json:"items"`
}

type AdminRefundListReq struct {
	Page     int64  `form:"page,optional,default=1"`
	PageSize int64  `form:"page_size,optional,default=20"`
	Status   int64  `form:"status,optional,default=-1"`
	UserId   int64  `form:"user_id,optional"`
	OrderId  string `form:"order_id,optional"`
}

type AdminRefundItem struct {
	RefundId        string `json:"refund_id"`
	OrderId         string `json:"order_id"`
	PaymentOrderId  string `json:"payment_order_id"`
	UserId          int64  `json:"user_id"`
	ProductId       int64  `json:"product_id"`
	RefundAmountFen int64  `json:"refund_amount_fen"`
	Status          int64  `json:"status"`
	StatusText      string `json:"status_text"`
	Reason          string `json:"reason"`
	AuditRemark     string `json:"audit_remark"`
	OperatorId      int64  `json:"operator_id"`
	RequestTime     string `json:"request_time"`
	AuditTime       string `json:"audit_time"`
	FinishTime      string `json:"finish_time"`
}

type AdminRefundListResp struct {
	Items []AdminRefundItem `json:"items"`
	Total int64             `json:"total"`
}

type AdminRefundAuditReq struct {
	RefundId string `json:"refund_id"`
	Approve  bool   `json:"approve"`
	Remark   string `json:"remark,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type AdminRefundAuditResp struct {
	RefundId string `json:"refund_id"`
	Status   string `json:"status"`
}

type AdminReconciliationReq struct {
	Page      int64  `form:"page,optional,default=1"`
	PageSize  int64  `form:"page_size,optional,default=20"`
	Status    int64  `form:"status,optional,default=-1"`
	IssueType string `form:"issue_type,optional"`
	OrderId   string `form:"order_id,optional"`
}

type AdminReconciliationItem struct {
	Id                int64  `json:"id"`
	IssueType         string `json:"issue_type"`
	OrderId           string `json:"order_id"`
	PaymentOrderId    string `json:"payment_order_id"`
	RefundOrderId     string `json:"refund_order_id"`
	ExpectedAmountFen int64  `json:"expected_amount_fen"`
	ActualAmountFen   int64  `json:"actual_amount_fen"`
	Severity          int64  `json:"severity"`
	Status            int64  `json:"status"`
	Detail            string `json:"detail"`
	CreateTime        string `json:"create_time"`
}

type AdminReconciliationResp struct {
	Items []AdminReconciliationItem `json:"items"`
	Total int64                     `json:"total"`
}

type AdminProductListReq struct {
	Page            int64  `form:"page,optional,default=1"`
	PageSize        int64  `form:"page_size,optional,default=20"`
	ProductId       int64  `form:"product_id,optional"`
	SupplierId      int64  `form:"supplier_id,optional"`
	Status          int64  `form:"status,optional,default=-1"`
	PromotionStatus int64  `form:"promotion_status,optional,default=-1"`
	StockStatus     string `form:"stock_status,optional"`
	Keyword         string `form:"keyword,optional"`
}

type AdminProductItem struct {
	ProductId         int64  `json:"product_id"`
	Name              string `json:"name"`
	ImageUrl          string `json:"image_url"`
	OriginPriceFen    int64  `json:"origin_price_fen"`
	SalePriceFen      int64  `json:"sale_price_fen"`
	SupplierId        int64  `json:"supplier_id"`
	SupplierName      string `json:"supplier_name"`
	StockAvailable    int64  `json:"stock_available"`
	PromotionPriceFen int64  `json:"promotion_price_fen"`
	PromotionType     string `json:"promotion_type"`
	PromotionTag      string `json:"promotion_tag"`
	Status            int64  `json:"status"`
	StatusText        string `json:"status_text"`
}

type AdminProductListResp struct {
	Items []AdminProductItem `json:"items"`
	Total int64              `json:"total"`
}

type AdminProductCreateReq struct {
	Name           string `json:"name"`
	ImageUrl       string `json:"image_url,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	OriginPriceFen int64  `json:"origin_price_fen"`
	SalePriceFen   int64  `json:"sale_price_fen"`
	StockAvailable int64  `json:"stock_available,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	SupplierId     int64  `json:"supplier_id,optional"`     //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	Status         int64  `json:"status,optional"`          //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type AdminProductCreateResp struct {
	ProductId int64 `json:"product_id"`
}

type AdminProductStockAdjustReq struct {
	ProductId int64 `json:"product_id"`
	Delta     int64 `json:"delta"`
	BucketIdx int64 `json:"bucket_idx,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type AdminProductStockAdjustResp struct {
	ProductId      int64 `json:"product_id"`
	StockAvailable int64 `json:"stock_available"`
}

type AdminSupplierListReq struct {
	Page     int64  `form:"page,optional,default=1"`
	PageSize int64  `form:"page_size,optional,default=20"`
	Status   int64  `form:"status,optional,default=-1"`
	Keyword  string `form:"keyword,optional"`
}

type AdminSupplierItem struct {
	SupplierId     int64  `json:"supplier_id"`
	Name           string `json:"name"`
	Status         int64  `json:"status"`
	StatusText     string `json:"status_text"`
	ProductCount   int64  `json:"product_count"`
	ActiveProducts int64  `json:"active_products"`
}

type AdminSupplierListResp struct {
	Items []AdminSupplierItem `json:"items"`
	Total int64               `json:"total"`
}

type AdminSupplierDetailReq struct {
	SupplierId int64 `form:"supplier_id"`
}

type AdminSupplierCreateReq struct {
	Name   string `json:"name"`
	Status int64  `json:"status,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type AdminSupplierCreateResp struct {
	SupplierId int64 `json:"supplier_id"`
}

type AdminSupplierUpdateReq struct {
	SupplierId int64  `json:"supplier_id"`
	Name       string `json:"name,optional"`   //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	Status     *int64 `json:"status,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type AdminPromotionListReq struct {
	Page         int64  `form:"page,optional,default=1"`
	PageSize     int64  `form:"page_size,optional,default=20"`
	ProductId    int64  `form:"product_id,optional"`
	Status       int64  `form:"status,optional,default=-1"`
	EffectStatus string `form:"effect_status,optional"`
	Keyword      string `form:"keyword,optional"`
}

type AdminPromotionItem struct {
	PromotionId      int64  `json:"promotion_id"`
	ProductId        int64  `json:"product_id"`
	ProductName      string `json:"product_name"`
	OriginPriceFen   int64  `json:"origin_price_fen"`
	SalePriceFen     int64  `json:"sale_price_fen"`
	Type             string `json:"type"`
	DiscountValue    int64  `json:"discount_value"`
	ThresholdAmount  int64  `json:"threshold_amount"`
	StartsAt         string `json:"starts_at"`
	EndsAt           string `json:"ends_at"`
	EffectStatus     string `json:"effect_status"`
	EffectStatusText string `json:"effect_status_text"`
	Status           int64  `json:"status"`
	StatusText       string `json:"status_text"`
}

type AdminPromotionListResp struct {
	Items []AdminPromotionItem `json:"items"`
	Total int64                `json:"total"`
}

type AdminPromotionDetailReq struct {
	PromotionId int64 `form:"promotion_id"`
}

type AdminPromotionCreateReq struct {
	ProductId       int64  `json:"product_id"`
	Type            string `json:"type,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	DiscountValue   int64  `json:"discount_value"`
	ThresholdAmount int64  `json:"threshold_amount,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	StartsAt        string `json:"starts_at,optional"`        //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	EndsAt          string `json:"ends_at,optional"`          //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	Status          int64  `json:"status,optional"`           //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type AdminPromotionCreateResp struct {
	PromotionId int64 `json:"promotion_id"`
}

type AdminPromotionUpdateReq struct {
	PromotionId     int64  `json:"promotion_id"`
	ProductId       *int64 `json:"product_id,optional"`       //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	DiscountValue   *int64 `json:"discount_value,optional"`   //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	ThresholdAmount *int64 `json:"threshold_amount,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	StartsAt        string `json:"starts_at,optional"`        //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	EndsAt          string `json:"ends_at,optional"`          //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	Status          *int64 `json:"status,optional"`           //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type AdminCampaignListReq struct {
	Page      int64  `form:"page,optional,default=1"`
	PageSize  int64  `form:"page_size,optional,default=20"`
	ProductId int64  `form:"product_id,optional"`
	Status    int64  `form:"status,optional,default=-1"`
	Keyword   string `form:"keyword,optional"`
}

type AdminCampaignItem struct {
	CampaignId    int64  `json:"campaign_id"`
	ProductId     int64  `json:"product_id"`
	ProductName   string `json:"product_name"`
	Name          string `json:"name"`
	CampaignStock int64  `json:"campaign_stock"`
	PerUserLimit  int64  `json:"per_user_limit"`
	StartsAt      string `json:"starts_at"`
	EndsAt        string `json:"ends_at"`
	Status        int64  `json:"status"`
	StatusText    string `json:"status_text"`
}

type AdminCampaignListResp struct {
	Items []AdminCampaignItem `json:"items"`
	Total int64               `json:"total"`
}

type AdminCampaignUpsertReq struct {
	CampaignId    int64  `json:"campaign_id,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	ProductId     int64  `json:"product_id"`
	Name          string `json:"name"`
	CampaignStock int64  `json:"campaign_stock"`
	PerUserLimit  int64  `json:"per_user_limit"`
	StartsAt      string `json:"starts_at,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	EndsAt        string `json:"ends_at,optional"`   //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	Status        int64  `json:"status,optional"`    //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type AdminCampaignUpsertResp struct {
	CampaignId int64 `json:"campaign_id"`
}

type AdminUserListReq struct {
	Page     int64  `form:"page,optional,default=1"`
	PageSize int64  `form:"page_size,optional,default=20"`
	Status   int64  `form:"status,optional"`
	Role     string `form:"role,optional"`
	Keyword  string `form:"keyword,optional"`
}

type AdminUserDetailReq struct {
	UserId int64 `form:"user_id"`
}

type AdminUserItem struct {
	UserId      int64  `json:"user_id"`
	DisplayName string `json:"display_name"`
	Phone       string `json:"phone"`
	Role        string `json:"role"`
	Status      int64  `json:"status"`
	StatusText  string `json:"status_text"`
	CreateTime  string `json:"create_time"`
}

type AdminUserListResp struct {
	Items []AdminUserItem `json:"items"`
	Total int64           `json:"total"`
}

type AdminDashboardStats struct {
	TotalOrders        int64 `json:"total_orders"`
	TotalRevenueFen    int64 `json:"total_revenue_fen"`
	TotalUsers         int64 `json:"total_users"`
	TotalProducts      int64 `json:"total_products"`
	TotalSuppliers     int64 `json:"total_suppliers"`
	TotalPromotions    int64 `json:"total_promotions"`
	ActivePromotions   int64 `json:"active_promotions"`
	LowStockProducts   int64 `json:"low_stock_products"`
	OutOfStockProducts int64 `json:"out_of_stock_products"`
	PendingOrders      int64 `json:"pending_orders"`
	PaidOrders         int64 `json:"paid_orders"`
	ShippedOrders      int64 `json:"shipped_orders"`
	CompletedOrders    int64 `json:"completed_orders"`
	RefundRequested    int64 `json:"refund_requested"`
	RefundedOrders     int64 `json:"refunded_orders"`
	OpenReconIssues    int64 `json:"open_reconciliation_issues"`
	PendingEvents      int64 `json:"pending_events"`
	DeadEvents         int64 `json:"dead_events"`
}

type UserAddressListResp struct {
	Items []UserAddressItem `json:"items"`
}

type UserAddressItem struct {
	AddressId     int64  `json:"address_id"`
	ReceiverName  string `json:"receiver_name"`
	ReceiverPhone string `json:"receiver_phone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	Detail        string `json:"detail"`
	IsDefault     bool   `json:"is_default"`
}

type UserAddressUpsertReq struct {
	AddressId     int64  `json:"address_id,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	ReceiverName  string `json:"receiver_name"`
	ReceiverPhone string `json:"receiver_phone"`
	Province      string `json:"province,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	City          string `json:"city,optional"`     //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	District      string `json:"district,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
	Detail        string `json:"detail"`
	IsDefault     bool   `json:"is_default,optional"` //nolint:staticcheck // go-zero httpx.Parse uses optional in json tags.
}

type UserAddressUpsertResp struct {
	AddressId int64 `json:"address_id"`
}

type AdminEventListReq struct {
	Page        int64  `form:"page,optional,default=1"`
	PageSize    int64  `form:"page_size,optional,default=20"`
	Status      int64  `form:"status,optional,default=-1"`
	EventType   string `form:"event_type,optional"`
	AggregateId string `form:"aggregate_id,optional"`
}

type AdminEventItem struct {
	Id           int64  `json:"id"`
	EventId      string `json:"event_id"`
	EventType    string `json:"event_type"`
	AggregateId  string `json:"aggregate_id"`
	Status       int64  `json:"status"`
	AttemptCount int64  `json:"attempt_count"`
	LastError    string `json:"last_error"`
	CreateTime   string `json:"create_time"`
	UpdateTime   string `json:"update_time"`
}

type AdminEventListResp struct {
	Items []AdminEventItem `json:"items"`
	Total int64            `json:"total"`
}

type AdminEventRetryReq struct {
	EventId string `json:"event_id"`
}

type AdminEventRetryResp struct {
	EventId string `json:"event_id"`
	Status  string `json:"status"`
}

type SecurityEventItem struct {
	EventType string `json:"event_type"`
	Result    string `json:"result"`
	UserId    int64  `json:"user_id"`
	Subject   string `json:"subject"`
	Ip        string `json:"ip"`
	UserAgent string `json:"user_agent"`
	CreatedAt int64  `json:"created_at"`
}

type SecurityEventsRecentReq struct {
	Limit     int64  `form:"limit,optional,default=20"`
	UserId    int64  `form:"user_id,optional"`
	EventType string `form:"event_type,optional"`
	Result    string `form:"result,optional"`
	Keyword   string `form:"keyword,optional"`
}

type SecurityEventsRecentResp struct {
	Items []SecurityEventItem `json:"items"`
}
