// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"flash-mall/app/order/api/internal/middleware"
	"flash-mall/app/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: HomeUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shop",
				Handler: ShopUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/debug",
				Handler: DebugUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/system/health",
				Handler: SystemHealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/login"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login/code",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/login/code"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/register",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/register"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/refresh",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/refresh"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/logout",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/logout"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/logout-all",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/logout-all"),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/auth/me",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/me"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/code/send",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/code/send"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/password/forgot",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/password/forgot"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/password/reset",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/password/reset"),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				middleware.NewRateLimitMiddleware(serverCtx.OrderLimiter),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/order/create",
				Handler: CreateOrderHandler(serverCtx),
			},
		),
		rest.WithJwt(serverCtx.Config.JwtAuthSecret),
	)
}
