// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"flash-mall/app/order/api/internal/middleware"
	"flash-mall/app/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: HomeUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shop",
				Handler: ShopUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/debug",
				Handler: DebugUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin",
				Handler: AdminUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/*any",
				Handler: AdminUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/monitor",
				Handler: MonitorUIHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/system/health",
				Handler: SystemHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/shop/catalog",
				Handler: CatalogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/order/status",
				Handler: OrderStatusPollHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: MetricsHandler(),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/login"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login/code",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/login/code"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/register",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/register"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/refresh",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/refresh"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/logout",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/logout"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/logout-all",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/logout-all"),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/auth/me",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/me"),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/auth/security/events/recent",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/security/events/recent"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/code/send",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/code/send"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/password/forgot",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/password/forgot"),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/password/reset",
				Handler: AuthProxyHandler(serverCtx, "/api/auth/password/reset"),
			},
		},
	)

	// Rate-limited order endpoints (JWT protected)
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				middleware.NewRateLimitMiddleware(serverCtx.OrderLimiter),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/order/create",
				Handler: CreateOrderHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/order/pay",
				Handler: PayOrderHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/api/order/detail",
				Handler: OrderDetailHandler(serverCtx),
			},
		),
		rest.WithJwt(serverCtx.Config.JwtAuthSecret),
	)
	// JWT-protected order query endpoints (no rate limit needed)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/orders",
				Handler: OrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/orders/detail",
				Handler: OrderDetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuthSecret),
	)

	// JWT-protected order lifecycle endpoints
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/order/ship",
				Handler: ShipOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/confirm-receipt",
				Handler: ConfirmReceiptHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/refund",
				Handler: RefundOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuthSecret),
	)

	// Admin API routes (JWT + admin role required)
	adminMW := []rest.Middleware{middleware.NewAdminAuthMiddleware()}
	server.AddRoutes(
		rest.WithMiddlewares(adminMW,
			rest.Route{Method: http.MethodGet, Path: "/api/admin/orders", Handler: AdminOrderListHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/api/admin/orders/detail", Handler: AdminOrderDetailHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/api/admin/orders/ship", Handler: AdminShipOrderHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/api/admin/orders/refund", Handler: AdminRefundOrderHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/api/admin/payments/reconcile", Handler: AdminPaymentReconcileHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/api/admin/products", Handler: AdminProductListHandler(serverCtx)},
			rest.Route{Method: http.MethodPost, Path: "/api/admin/products/update", Handler: AdminProductUpdateHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/api/admin/users", Handler: AdminUserListHandler(serverCtx)},
			rest.Route{Method: http.MethodGet, Path: "/api/admin/dashboard/stats", Handler: AdminDashboardStatsHandler(serverCtx)},
		),
		rest.WithJwt(serverCtx.Config.JwtAuthSecret),
	)
}
