package handler

func routeMigrationStatus() RouteMigrationStatusResp {
	return RouteMigrationStatusResp{
		Groups: []RouteMigrationGroup{
			{
				Name:   "system",
				Status: "partial",
				LiveRoutes: []string{
					"GET /health",
					"GET /api/system/health",
					"GET /api/system/migration/routes",
					"GET /metrics",
				},
				PlannedRoutes: []string{
					"GET /monitor",
				},
				Notes: "Health, migration visibility, and aggregate Prometheus metrics are Hertz-native; deployment should keep metrics behind an internal network policy.",
			},
			{
				Name:   "shop",
				Status: "live",
				LiveRoutes: []string{
					"GET /",
					"GET /shop",
					"GET /product/*any",
					"GET /store/*any",
					"GET /uploads/products/*any",
					"GET /uploads/stores/*any",
					"GET /api/shop/catalog",
					"GET /api/shop/products",
					"GET /api/shop/products/detail",
					"GET /api/shop/stores/detail",
					"GET /api/shop/stores/products",
					"GET /api/user/addresses",
					"POST /api/user/addresses/upsert",
				},
				Notes: "Public pages and store/showcase orchestration are Hertz-native; product reads deliberately remain on go-zero product-rpc and product_card_snapshot to avoid an extra Kitex hop on the high-frequency read path.",
			},
			{
				Name:   "auth",
				Status: "live",
				LiveRoutes: []string{
					"POST /api/auth/login",
					"POST /api/auth/login/code",
					"POST /api/auth/register",
					"POST /api/auth/refresh",
					"POST /api/auth/logout",
					"POST /api/auth/logout-all",
					"GET /api/auth/me",
					"GET /api/auth/security/events/recent",
					"POST /api/auth/code/send",
					"POST /api/auth/password/forgot",
					"POST /api/auth/password/reset",
				},
				Notes: "Hertz is the external auth entry; auth-api remains the credential, session, and audit owner.",
			},
			{
				Name:   "payments",
				Status: "live",
				LiveRoutes: []string{
					"POST /api/payment/callback",
					"GET /api/payment/status",
					"POST /api/payment/sandbox/confirm",
				},
				Notes: "Hertz validates provider callbacks and exposes payment status; payment state transitions and idempotency remain owned by order-rpc.",
			},
			{
				Name:   "inventory",
				Status: "live",
				LiveRoutes: []string{
					"GET /api/inventory/summary",
					"GET /api/admin/inventory/stock-changes",
					"POST /api/admin/inventory/stock-snapshots/rebuild",
					"GET /api/merchant/inventory/stock-changes",
				},
				Notes: "Inventory writes are internal order-rpc to inventory-kitex commands; Hertz exposes read and role-protected audit surfaces only.",
			},
			{
				Name:   "orders",
				Status: "live",
				LiveRoutes: []string{
					"POST /api/order/create",
					"POST /api/order/pay",
					"POST /api/order/cancel",
					"POST /api/order/refund",
					"POST /api/order/confirm-receipt",
					"GET /api/order/detail",
					"GET /api/orders",
					"GET /api/orders/detail",
					"GET /api/order/status",
				},
				Notes: "User order create, payment callback, status polling, cancel, refund request, confirm receipt, list, and detail enter through Hertz; timeout-close remains an internal order-rpc responsibility rather than another public route.",
			},
			{
				Name:   "admin",
				Status: "live",
				LiveRoutes: []string{
					"GET /api/admin/showcase",
					"GET /api/admin/showcase/candidates",
					"POST /api/admin/showcase/publish",
					"GET /api/admin/merchants/applications",
					"POST /api/admin/merchants/applications/audit",
					"GET /api/admin/campaigns",
					"POST /api/admin/campaigns/upsert",
					"GET /api/admin/products",
					"GET /api/admin/products/detail",
					"POST /api/admin/products/create",
					"POST /api/admin/products/inventory-seed/retry",
					"POST /api/admin/products/update",
					"POST /api/admin/products/stock-adjust",
					"POST /api/admin/products/card-snapshots/refresh",
					"POST /api/admin/products/image",
					"GET /api/admin/suppliers",
					"GET /api/admin/suppliers/detail",
					"POST /api/admin/suppliers/create",
					"POST /api/admin/suppliers/update",
					"GET /api/admin/promotions",
					"GET /api/admin/promotions/detail",
					"POST /api/admin/promotions/create",
					"POST /api/admin/promotions/update",
					"GET /api/admin/orders",
					"GET /api/admin/orders/detail",
					"GET /api/admin/orders/status-logs",
					"POST /api/admin/orders/ship",
					"POST /api/admin/orders/close",
					"POST /api/admin/orders/refund",
					"GET /api/admin/refunds",
					"POST /api/admin/refunds/audit",
					"GET /api/admin/dashboard/stats",
					"GET /api/admin/reconciliation/issues",
					"POST /api/admin/reconciliation/scan",
					"GET /api/admin/events",
					"POST /api/admin/events/retry",
					"GET /api/admin/users",
					"GET /api/admin/users/detail",
					"POST /api/admin/users/status",
					"GET /api/admin/security/events/recent",
				},
				Notes: "Admin showcase, merchant onboarding, campaign, inventory audit, product/supplier/promotion, order/refund, dashboard, reconciliation, outbox event, user management, and auth security log operations are Hertz-native.",
			},
			{
				Name:   "merchant",
				Status: "live",
				LiveRoutes: []string{
					"GET /api/merchant/me",
					"GET /api/merchant/application",
					"POST /api/merchant/apply",
					"GET /api/merchant/store/profile",
					"POST /api/merchant/store/profile",
					"POST /api/merchant/store/assets",
					"GET /api/merchant/dashboard/stats",
					"GET /api/merchant/products",
					"POST /api/merchant/products/create",
					"POST /api/merchant/products/inventory-seed/retry",
					"POST /api/merchant/products/update",
					"POST /api/merchant/products/stock-adjust",
					"POST /api/merchant/products/image",
					"GET /api/merchant/orders",
					"POST /api/merchant/orders/ship",
					"GET /api/merchant/refunds",
				},
				Notes: "Merchant store/profile and operational surfaces are Hertz-native. Product reads remain go-zero RPC; inventory write commands remain internal Kitex inventory commands with idempotency and audit independent of transport.",
			},
		},
	}
}
