package handler

import (
	"time"

	"flash-mall/app/gateway/hertz/internal/middleware"
	"flash-mall/app/gateway/hertz/internal/svc"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func RegisterRoutes(h *server.Hertz, svcCtx *svc.ServiceContext, startedAt time.Time) {
	h.Use(middleware.Recover(), middleware.Trace(), middleware.AccessLog())

	registerSystemRoutes(h, svcCtx, startedAt)
	registerAuthRoutes(h, svcCtx)
	registerShopRoutes(h, svcCtx)
	registerInventoryRoutes(h, svcCtx)
	registerOrderRoutes(h, svcCtx)
	registerAdminRoutes(h, svcCtx)
	registerMerchantRoutes(h, svcCtx)
	registerCompatibilityRoutes(h, svcCtx, startedAt)
}

func registerSystemRoutes(h *server.Hertz, svcCtx *svc.ServiceContext, startedAt time.Time) {
	h.GET("/", StaticPageHandler("home.html"))
	h.GET("/shop", StaticPageHandler("shop.html"))
	h.GET("/pay", StaticPageHandler("shop.html"))
	h.GET("/product/*any", StaticPageHandler("shop.html"))
	h.GET("/store/*any", StaticPageHandler("shop.html"))
	h.GET("/admin", StaticPageHandler("admin.html"))
	h.GET("/admin/*any", StaticPageHandler("admin.html"))
	h.GET("/merchant", StaticPageHandler("merchant.html"))
	h.GET("/merchant/*any", StaticPageHandler("merchant.html"))
	h.GET("/health", HealthHandler(svcCtx, startedAt))
	h.GET("/api/system/health", HealthHandler(svcCtx, startedAt))
	h.GET("/api/system/migration/routes", RouteMigrationStatusHandler())
	h.GET("/metrics", MetricsHandler())
}

func registerShopRoutes(h *server.Hertz, svcCtx *svc.ServiceContext) {
	h.GET("/products/*any", StaticAssetHandler("products"))
	h.GET("/uploads/products/*any", ProductUploadStaticHandler(svcCtx))
	h.GET("/uploads/stores/*any", StoreUploadStaticHandler(svcCtx))
	h.GET("/api/shop/catalog", CatalogHandler(svcCtx))
	h.GET("/api/shop/products", ProductListHandler(svcCtx, true))
	h.GET("/api/shop/products/detail", ProductDetailHandler(svcCtx))
	h.GET("/api/shop/stores/detail", StoreDetailHandler(svcCtx))
	h.GET("/api/shop/stores/products", StoreProductListHandler(svcCtx))
	h.GET("/api/user/addresses", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), UserAddressListHandler(svcCtx))
	h.POST("/api/user/addresses/upsert", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), UserAddressUpsertHandler(svcCtx))
}

func registerAuthRoutes(h *server.Hertz, svcCtx *svc.ServiceContext) {
	h.POST("/api/auth/login", AuthProxyHandler(svcCtx, "/api/auth/login"))
	h.POST("/api/auth/login/code", AuthProxyHandler(svcCtx, "/api/auth/login/code"))
	h.POST("/api/auth/register", AuthProxyHandler(svcCtx, "/api/auth/register"))
	h.POST("/api/auth/refresh", AuthProxyHandler(svcCtx, "/api/auth/refresh"))
	h.POST("/api/auth/logout", AuthProxyHandler(svcCtx, "/api/auth/logout"))
	h.POST("/api/auth/logout-all", AuthProxyHandler(svcCtx, "/api/auth/logout-all"))
	h.GET("/api/auth/me", AuthProxyHandler(svcCtx, "/api/auth/me"))
	h.GET("/api/auth/security/events/recent", AuthProxyHandler(svcCtx, "/api/auth/security/events/recent"))
	h.POST("/api/auth/code/send", AuthProxyHandler(svcCtx, "/api/auth/code/send"))
	h.POST("/api/auth/password/forgot", AuthProxyHandler(svcCtx, "/api/auth/password/forgot"))
	h.POST("/api/auth/password/reset", AuthProxyHandler(svcCtx, "/api/auth/password/reset"))
	h.POST("/api/payment/callback", PaymentCallbackHandler(svcCtx))
	h.GET("/api/payment/status", middleware.OptionalIdentity(svcCtx.Config.JwtAuthSecret), PaymentStatusHandler(svcCtx))
	h.POST("/api/payment/sandbox/confirm", SandboxPaymentConfirmHandler(svcCtx))
}

func registerInventoryRoutes(h *server.Hertz, svcCtx *svc.ServiceContext) {
	h.GET("/api/inventory/summary", InventorySummaryHandler(svcCtx))
}

func registerOrderRoutes(h *server.Hertz, svcCtx *svc.ServiceContext) {
	h.GET("/api/order/status", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderStatusPollHandler(svcCtx))
	h.POST("/api/order/create", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), CreateOrderHandler(svcCtx))
	h.POST("/api/order/pay", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), PayOrderHandler(svcCtx))
	h.POST("/api/order/cancel", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), CancelOrderHandler(svcCtx))
	h.POST("/api/order/refund", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), RefundOrderHandler(svcCtx))
	h.POST("/api/order/confirm-receipt", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), ConfirmReceiptHandler(svcCtx))
	h.GET("/api/order/detail", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderDetailHandler(svcCtx))
	h.GET("/api/orders", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderListHandler(svcCtx))
	h.GET("/api/orders/detail", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderDetailHandler(svcCtx))
}

func registerAdminRoutes(h *server.Hertz, svcCtx *svc.ServiceContext) {
	h.GET("/api/admin/showcase", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminShowcaseHandler(svcCtx))
	h.GET("/api/admin/showcase/candidates", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminShowcaseCandidatesHandler(svcCtx))
	h.POST("/api/admin/showcase/publish", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminShowcasePublishHandler(svcCtx))
	h.GET("/api/admin/merchants/applications", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminMerchantApplyListHandler(svcCtx))
	h.POST("/api/admin/merchants/applications/audit", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminMerchantApplyAuditHandler(svcCtx))
	h.GET("/api/admin/campaigns", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminCampaignListHandler(svcCtx))
	h.POST("/api/admin/campaigns/upsert", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminCampaignUpsertHandler(svcCtx))
	h.GET("/api/admin/products", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductListHandler(svcCtx))
	h.GET("/api/admin/inventory/stock-changes", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminStockChangeLogHandler(svcCtx))
	h.POST("/api/admin/inventory/stock-snapshots/rebuild", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminStockSnapshotRebuildHandler(svcCtx))
	h.GET("/api/admin/products/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductDetailHandler(svcCtx))
	h.POST("/api/admin/products/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductCreateHandler(svcCtx))
	h.POST("/api/admin/products/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductUpdateHandler(svcCtx))
	h.POST("/api/admin/products/stock-adjust", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductStockAdjustHandler(svcCtx))
	h.POST("/api/admin/products/card-snapshots/refresh", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductCardSnapshotRefreshHandler(svcCtx))
	h.POST("/api/admin/products/image", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductImageUploadHandler(svcCtx))
	h.GET("/api/admin/suppliers", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierListHandler(svcCtx))
	h.GET("/api/admin/suppliers/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierDetailHandler(svcCtx))
	h.POST("/api/admin/suppliers/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierCreateHandler(svcCtx))
	h.POST("/api/admin/suppliers/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierUpdateHandler(svcCtx))
	h.GET("/api/admin/promotions", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionListHandler(svcCtx))
	h.GET("/api/admin/promotions/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionDetailHandler(svcCtx))
	h.POST("/api/admin/promotions/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionCreateHandler(svcCtx))
	h.POST("/api/admin/promotions/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionUpdateHandler(svcCtx))
	h.GET("/api/admin/orders", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderListHandler(svcCtx))
	h.GET("/api/admin/orders/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderDetailHandler(svcCtx))
	h.GET("/api/admin/orders/status-logs", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderStatusLogHandler(svcCtx))
	h.POST("/api/admin/orders/ship", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminShipOrderHandler(svcCtx))
	h.POST("/api/admin/orders/close", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminCloseOrderHandler(svcCtx))
	h.POST("/api/admin/orders/refund", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundOrderHandler(svcCtx))
	h.GET("/api/admin/refunds", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundListHandler(svcCtx))
	h.POST("/api/admin/refunds/audit", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundAuditHandler(svcCtx))
	h.GET("/api/admin/dashboard/stats", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminDashboardStatsHandler(svcCtx))
	h.GET("/api/admin/reconciliation/issues", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminReconciliationListHandler(svcCtx))
	h.POST("/api/admin/reconciliation/scan", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminReconciliationScanHandler(svcCtx))
	h.GET("/api/admin/events", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminEventListHandler(svcCtx))
	h.POST("/api/admin/events/retry", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminEventRetryHandler(svcCtx))
	h.GET("/api/admin/users", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users"))
	h.GET("/api/admin/users/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users/detail"))
	h.POST("/api/admin/users/status", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users/status"))
	h.GET("/api/admin/security/events/recent", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/security/events/recent"))
}

func registerMerchantRoutes(h *server.Hertz, svcCtx *svc.ServiceContext) {
	h.GET("/api/merchant/me", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantMeHandler(svcCtx))
	h.GET("/api/merchant/application", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantApplicationHandler(svcCtx))
	h.POST("/api/merchant/apply", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantApplyCreateHandler(svcCtx))
	h.GET("/api/merchant/store/profile", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantStoreProfileHandler(svcCtx))
	h.POST("/api/merchant/store/profile", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantStoreUpdateHandler(svcCtx))
	h.POST("/api/merchant/store/assets", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantStoreAssetUploadHandler(svcCtx))
	h.GET("/api/merchant/dashboard/stats", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantDashboardStatsHandler(svcCtx))
	h.GET("/api/merchant/products", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductListHandler(svcCtx))
	h.POST("/api/merchant/products/create", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductCreateHandler(svcCtx))
	h.POST("/api/merchant/products/update", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductUpdateHandler(svcCtx))
	h.POST("/api/merchant/products/stock-adjust", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductStockAdjustHandler(svcCtx))
	h.POST("/api/merchant/products/image", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductImageUploadHandler(svcCtx))
	h.GET("/api/merchant/inventory/stock-changes", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantStockChangeLogHandler(svcCtx))
	h.GET("/api/merchant/orders", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantOrderListHandler(svcCtx))
	h.POST("/api/merchant/orders/ship", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantShipOrderHandler(svcCtx))
	h.GET("/api/merchant/refunds", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantRefundListHandler(svcCtx))
}

func registerCompatibilityRoutes(h *server.Hertz, svcCtx *svc.ServiceContext, startedAt time.Time) {
	h.GET("/api/gateway/health", HealthHandler(svcCtx, startedAt))
	h.GET("/api/catalog", CatalogHandler(svcCtx))
	h.GET("/api/gateway/products", ProductListHandler(svcCtx, true))
	h.GET("/api/gateway/products/detail", ProductDetailHandler(svcCtx))
	h.GET("/api/gateway/inventory/summary", InventorySummaryHandler(svcCtx))
	h.POST("/api/gateway/order/create", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), CreateOrderHandler(svcCtx))
	h.POST("/api/gateway/order/pay", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), PayOrderHandler(svcCtx))
	h.POST("/api/gateway/order/cancel", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), CancelOrderHandler(svcCtx))
	h.POST("/api/gateway/order/refund", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), RefundOrderHandler(svcCtx))
	h.POST("/api/gateway/order/confirm-receipt", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), ConfirmReceiptHandler(svcCtx))
	h.GET("/api/gateway/order/detail", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderDetailHandler(svcCtx))
	h.GET("/api/gateway/orders", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderListHandler(svcCtx))
	h.GET("/api/gateway/orders/detail", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderDetailHandler(svcCtx))
	h.GET("/api/gateway/admin/products", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductListHandler(svcCtx))
	h.GET("/api/gateway/admin/products/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductDetailHandler(svcCtx))
	h.POST("/api/gateway/admin/products/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductCreateHandler(svcCtx))
	h.POST("/api/gateway/admin/products/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductUpdateHandler(svcCtx))
	h.POST("/api/gateway/admin/products/stock-adjust", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductStockAdjustHandler(svcCtx))
	h.POST("/api/gateway/admin/products/card-snapshots/refresh", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductCardSnapshotRefreshHandler(svcCtx))
	h.POST("/api/gateway/admin/products/image", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductImageUploadHandler(svcCtx))
	h.GET("/api/gateway/admin/suppliers", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierListHandler(svcCtx))
	h.GET("/api/gateway/admin/suppliers/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierDetailHandler(svcCtx))
	h.POST("/api/gateway/admin/suppliers/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierCreateHandler(svcCtx))
	h.POST("/api/gateway/admin/suppliers/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierUpdateHandler(svcCtx))
	h.GET("/api/gateway/admin/promotions", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionListHandler(svcCtx))
	h.GET("/api/gateway/admin/promotions/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionDetailHandler(svcCtx))
	h.POST("/api/gateway/admin/promotions/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionCreateHandler(svcCtx))
	h.POST("/api/gateway/admin/promotions/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionUpdateHandler(svcCtx))
	h.GET("/api/gateway/admin/orders", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderListHandler(svcCtx))
	h.GET("/api/gateway/admin/orders/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderDetailHandler(svcCtx))
	h.GET("/api/gateway/admin/orders/status-logs", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderStatusLogHandler(svcCtx))
	h.POST("/api/gateway/admin/orders/ship", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminShipOrderHandler(svcCtx))
	h.POST("/api/gateway/admin/orders/close", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminCloseOrderHandler(svcCtx))
	h.POST("/api/gateway/admin/orders/refund", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundOrderHandler(svcCtx))
	h.GET("/api/gateway/admin/refunds", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundListHandler(svcCtx))
	h.POST("/api/gateway/admin/refunds/audit", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundAuditHandler(svcCtx))
	h.GET("/api/gateway/admin/dashboard/stats", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminDashboardStatsHandler(svcCtx))
	h.GET("/api/gateway/admin/reconciliation/issues", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminReconciliationListHandler(svcCtx))
	h.POST("/api/gateway/admin/reconciliation/scan", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminReconciliationScanHandler(svcCtx))
	h.GET("/api/gateway/admin/events", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminEventListHandler(svcCtx))
	h.POST("/api/gateway/admin/events/retry", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminEventRetryHandler(svcCtx))
	h.GET("/api/gateway/admin/users", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users"))
	h.GET("/api/gateway/admin/users/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users/detail"))
	h.POST("/api/gateway/admin/users/status", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users/status"))
	h.GET("/api/gateway/admin/security/events/recent", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/security/events/recent"))
	h.GET("/api/gateway/merchant/me", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantMeHandler(svcCtx))
	h.GET("/api/gateway/merchant/application", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantApplicationHandler(svcCtx))
	h.POST("/api/gateway/merchant/apply", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantApplyCreateHandler(svcCtx))
	h.GET("/api/gateway/merchant/dashboard/stats", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantDashboardStatsHandler(svcCtx))
	h.GET("/api/gateway/merchant/products", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductListHandler(svcCtx))
	h.POST("/api/gateway/merchant/products/create", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductCreateHandler(svcCtx))
	h.POST("/api/gateway/merchant/products/update", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductUpdateHandler(svcCtx))
	h.POST("/api/gateway/merchant/products/stock-adjust", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductStockAdjustHandler(svcCtx))
	h.GET("/api/gateway/merchant/orders", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantOrderListHandler(svcCtx))
	h.POST("/api/gateway/merchant/orders/ship", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantShipOrderHandler(svcCtx))
	h.GET("/api/gateway/merchant/refunds", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantRefundListHandler(svcCtx))
}
