package handler

import (
	"time"

	"flash-mall/app/gateway/hertz/internal/middleware"
	"flash-mall/app/gateway/hertz/internal/svc"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func registerCompatibilityRoutes(h *server.Hertz, svcCtx *svc.ServiceContext, startedAt time.Time) {
	h.GET("/api/gateway/health", HealthHandler(svcCtx, startedAt))
	h.GET("/api/catalog", CatalogHandler(svcCtx))
	h.GET("/api/gateway/products", ProductListHandler(svcCtx, true))
	h.GET("/api/gateway/products/detail", ProductDetailHandler(svcCtx))
	h.GET("/api/gateway/inventory/summary", InventorySummaryHandler(svcCtx))
	h.POST("/api/gateway/order/create", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), CreateOrderHandler(svcCtx))
	h.POST("/api/gateway/order/pay", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), PayOrderHandler(svcCtx))
	h.POST("/api/gateway/order/cancel", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), CancelOrderHandler(svcCtx))
	h.POST("/api/gateway/order/refund", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), RefundOrderHandler(svcCtx))
	h.POST("/api/gateway/order/confirm-receipt", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), ConfirmReceiptHandler(svcCtx))
	h.GET("/api/gateway/order/detail", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderDetailHandler(svcCtx))
	h.GET("/api/gateway/orders", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderListHandler(svcCtx))
	h.GET("/api/gateway/orders/detail", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), OrderDetailHandler(svcCtx))
	h.GET("/api/gateway/admin/products", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductListHandler(svcCtx))
	h.GET("/api/gateway/admin/products/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductDetailHandler(svcCtx))
	h.POST("/api/gateway/admin/products/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductCreateHandler(svcCtx))
	h.POST("/api/gateway/admin/products/inventory-seed/retry", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductInventorySeedRetryHandler(svcCtx))
	h.POST("/api/gateway/admin/products/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductUpdateHandler(svcCtx))
	h.POST("/api/gateway/admin/products/stock-adjust", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductStockAdjustHandler(svcCtx))
	h.POST("/api/gateway/admin/products/card-snapshots/refresh", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductCardSnapshotRefreshHandler(svcCtx))
	h.POST("/api/gateway/admin/products/image", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminProductImageUploadHandler(svcCtx))
	h.GET("/api/gateway/admin/suppliers", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierListHandler(svcCtx))
	h.GET("/api/gateway/admin/suppliers/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierDetailHandler(svcCtx))
	h.POST("/api/gateway/admin/suppliers/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierCreateHandler(svcCtx))
	h.POST("/api/gateway/admin/suppliers/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminSupplierUpdateHandler(svcCtx))
	h.GET("/api/gateway/admin/promotions", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionListHandler(svcCtx))
	h.GET("/api/gateway/admin/promotions/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionDetailHandler(svcCtx))
	h.POST("/api/gateway/admin/promotions/create", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionCreateHandler(svcCtx))
	h.POST("/api/gateway/admin/promotions/update", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminPromotionUpdateHandler(svcCtx))
	h.GET("/api/gateway/admin/orders", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderListHandler(svcCtx))
	h.GET("/api/gateway/admin/orders/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderDetailHandler(svcCtx))
	h.GET("/api/gateway/admin/orders/status-logs", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminOrderStatusLogHandler(svcCtx))
	h.POST("/api/gateway/admin/orders/ship", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminShipOrderHandler(svcCtx))
	h.POST("/api/gateway/admin/orders/close", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminCloseOrderHandler(svcCtx))
	h.POST("/api/gateway/admin/orders/refund", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundOrderHandler(svcCtx))
	h.GET("/api/gateway/admin/refunds", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundListHandler(svcCtx))
	h.POST("/api/gateway/admin/refunds/audit", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminRefundAuditHandler(svcCtx))
	h.GET("/api/gateway/admin/dashboard/stats", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminDashboardStatsHandler(svcCtx))
	h.GET("/api/gateway/admin/reconciliation/issues", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminReconciliationListHandler(svcCtx))
	h.POST("/api/gateway/admin/reconciliation/scan", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminReconciliationScanHandler(svcCtx))
	h.GET("/api/gateway/admin/events", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminEventListHandler(svcCtx))
	h.POST("/api/gateway/admin/events/retry", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AdminEventRetryHandler(svcCtx))
	h.GET("/api/gateway/admin/users", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users"))
	h.GET("/api/gateway/admin/users/detail", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users/detail"))
	h.POST("/api/gateway/admin/users/status", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/users/status"))
	h.GET("/api/gateway/admin/security/events/recent", middleware.RequireAdmin(svcCtx.Config.JwtAuthSecret), AuthProxyHandler(svcCtx, "/api/admin/security/events/recent"))
	h.GET("/api/gateway/merchant/me", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantMeHandler(svcCtx))
	h.GET("/api/gateway/merchant/application", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantApplicationHandler(svcCtx))
	h.POST("/api/gateway/merchant/apply", middleware.RequireUser(svcCtx.Config.JwtAuthSecret), MerchantApplyCreateHandler(svcCtx))
	h.GET("/api/gateway/merchant/dashboard/stats", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantDashboardStatsHandler(svcCtx))
	h.GET("/api/gateway/merchant/products", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductListHandler(svcCtx))
	h.POST("/api/gateway/merchant/products/create", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductCreateHandler(svcCtx))
	h.POST("/api/gateway/merchant/products/inventory-seed/retry", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductInventorySeedRetryHandler(svcCtx))
	h.POST("/api/gateway/merchant/products/update", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductUpdateHandler(svcCtx))
	h.POST("/api/gateway/merchant/products/stock-adjust", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantProductStockAdjustHandler(svcCtx))
	h.GET("/api/gateway/merchant/orders", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantOrderListHandler(svcCtx))
	h.POST("/api/gateway/merchant/orders/ship", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantShipOrderHandler(svcCtx))
	h.GET("/api/gateway/merchant/refunds", middleware.RequireMerchant(svcCtx.Config.JwtAuthSecret), MerchantRefundListHandler(svcCtx))
}
