// Code generated by Kitex v0.16.2. DO NOT EDIT.

package inventoryservice

import (
	"context"
	common "flash-mall/app/inventory/kitex/kitex_gen/flashmall/common"
	inventory "flash-mall/app/inventory/kitex/kitex_gen/flashmall/inventory"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetStock(ctx context.Context, req *inventory.GetStockRequest, callOptions ...callopt.Option) (r *inventory.GetStockResponse, err error)
	SeedStock(ctx context.Context, req *inventory.SeedStockRequest, callOptions ...callopt.Option) (r *common.Empty, err error)
	ReserveStock(ctx context.Context, req *inventory.ReserveStockRequest, callOptions ...callopt.Option) (r *common.Empty, err error)
	ConfirmDeduct(ctx context.Context, req *inventory.ConfirmDeductRequest, callOptions ...callopt.Option) (r *common.Empty, err error)
	ReleaseStock(ctx context.Context, req *inventory.ReleaseStockRequest, callOptions ...callopt.Option) (r *common.Empty, err error)
	ReconcileStock(ctx context.Context, req *inventory.ReconcileStockRequest, callOptions ...callopt.Option) (r *inventory.ReconcileStockResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kInventoryServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInventoryServiceClient struct {
	*kClient
}

func (p *kInventoryServiceClient) GetStock(ctx context.Context, req *inventory.GetStockRequest, callOptions ...callopt.Option) (r *inventory.GetStockResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStock(ctx, req)
}

func (p *kInventoryServiceClient) SeedStock(ctx context.Context, req *inventory.SeedStockRequest, callOptions ...callopt.Option) (r *common.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SeedStock(ctx, req)
}

func (p *kInventoryServiceClient) ReserveStock(ctx context.Context, req *inventory.ReserveStockRequest, callOptions ...callopt.Option) (r *common.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReserveStock(ctx, req)
}

func (p *kInventoryServiceClient) ConfirmDeduct(ctx context.Context, req *inventory.ConfirmDeductRequest, callOptions ...callopt.Option) (r *common.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmDeduct(ctx, req)
}

func (p *kInventoryServiceClient) ReleaseStock(ctx context.Context, req *inventory.ReleaseStockRequest, callOptions ...callopt.Option) (r *common.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseStock(ctx, req)
}

func (p *kInventoryServiceClient) ReconcileStock(ctx context.Context, req *inventory.ReconcileStockRequest, callOptions ...callopt.Option) (r *inventory.ReconcileStockResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReconcileStock(ctx, req)
}
