// Code generated by Kitex v0.16.2. DO NOT EDIT.

package inventoryservice

import (
	"context"
	"errors"
	common "flash-mall/app/inventory/kitex/kitex_gen/flashmall/common"
	inventory "flash-mall/app/inventory/kitex/kitex_gen/flashmall/inventory"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetStock": kitex.NewMethodInfo(
		getStockHandler,
		newInventoryServiceGetStockArgs,
		newInventoryServiceGetStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SeedStock": kitex.NewMethodInfo(
		seedStockHandler,
		newInventoryServiceSeedStockArgs,
		newInventoryServiceSeedStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReserveStock": kitex.NewMethodInfo(
		reserveStockHandler,
		newInventoryServiceReserveStockArgs,
		newInventoryServiceReserveStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfirmDeduct": kitex.NewMethodInfo(
		confirmDeductHandler,
		newInventoryServiceConfirmDeductArgs,
		newInventoryServiceConfirmDeductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReleaseStock": kitex.NewMethodInfo(
		releaseStockHandler,
		newInventoryServiceReleaseStockArgs,
		newInventoryServiceReleaseStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReconcileStock": kitex.NewMethodInfo(
		reconcileStockHandler,
		newInventoryServiceReconcileStockArgs,
		newInventoryServiceReconcileStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	inventoryServiceServiceInfo                = NewServiceInfo()
	inventoryServiceServiceInfoForClient       = NewServiceInfoForClient()
	inventoryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return inventoryServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return inventoryServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return inventoryServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InventoryService"
	handlerType := (*inventory.InventoryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "inventory",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func getStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceGetStockArgs)
	realResult := result.(*inventory.InventoryServiceGetStockResult)
	success, err := handler.(inventory.InventoryService).GetStock(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *common.BizException:
			realResult.Biz = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newInventoryServiceGetStockArgs() interface{} {
	return inventory.NewInventoryServiceGetStockArgs()
}

func newInventoryServiceGetStockResult() interface{} {
	return inventory.NewInventoryServiceGetStockResult()
}

func seedStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceSeedStockArgs)
	realResult := result.(*inventory.InventoryServiceSeedStockResult)
	success, err := handler.(inventory.InventoryService).SeedStock(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *common.BizException:
			realResult.Biz = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newInventoryServiceSeedStockArgs() interface{} {
	return inventory.NewInventoryServiceSeedStockArgs()
}

func newInventoryServiceSeedStockResult() interface{} {
	return inventory.NewInventoryServiceSeedStockResult()
}

func reserveStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceReserveStockArgs)
	realResult := result.(*inventory.InventoryServiceReserveStockResult)
	success, err := handler.(inventory.InventoryService).ReserveStock(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *common.BizException:
			realResult.Biz = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newInventoryServiceReserveStockArgs() interface{} {
	return inventory.NewInventoryServiceReserveStockArgs()
}

func newInventoryServiceReserveStockResult() interface{} {
	return inventory.NewInventoryServiceReserveStockResult()
}

func confirmDeductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceConfirmDeductArgs)
	realResult := result.(*inventory.InventoryServiceConfirmDeductResult)
	success, err := handler.(inventory.InventoryService).ConfirmDeduct(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *common.BizException:
			realResult.Biz = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newInventoryServiceConfirmDeductArgs() interface{} {
	return inventory.NewInventoryServiceConfirmDeductArgs()
}

func newInventoryServiceConfirmDeductResult() interface{} {
	return inventory.NewInventoryServiceConfirmDeductResult()
}

func releaseStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceReleaseStockArgs)
	realResult := result.(*inventory.InventoryServiceReleaseStockResult)
	success, err := handler.(inventory.InventoryService).ReleaseStock(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *common.BizException:
			realResult.Biz = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newInventoryServiceReleaseStockArgs() interface{} {
	return inventory.NewInventoryServiceReleaseStockArgs()
}

func newInventoryServiceReleaseStockResult() interface{} {
	return inventory.NewInventoryServiceReleaseStockResult()
}

func reconcileStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*inventory.InventoryServiceReconcileStockArgs)
	realResult := result.(*inventory.InventoryServiceReconcileStockResult)
	success, err := handler.(inventory.InventoryService).ReconcileStock(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *common.BizException:
			realResult.Biz = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newInventoryServiceReconcileStockArgs() interface{} {
	return inventory.NewInventoryServiceReconcileStockArgs()
}

func newInventoryServiceReconcileStockResult() interface{} {
	return inventory.NewInventoryServiceReconcileStockResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetStock(ctx context.Context, req *inventory.GetStockRequest) (r *inventory.GetStockResponse, err error) {
	var _args inventory.InventoryServiceGetStockArgs
	_args.Req = req
	var _result inventory.InventoryServiceGetStockResult
	if err = p.c.Call(ctx, "GetStock", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Biz != nil:
		return r, _result.Biz
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SeedStock(ctx context.Context, req *inventory.SeedStockRequest) (r *common.Empty, err error) {
	var _args inventory.InventoryServiceSeedStockArgs
	_args.Req = req
	var _result inventory.InventoryServiceSeedStockResult
	if err = p.c.Call(ctx, "SeedStock", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Biz != nil:
		return r, _result.Biz
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReserveStock(ctx context.Context, req *inventory.ReserveStockRequest) (r *common.Empty, err error) {
	var _args inventory.InventoryServiceReserveStockArgs
	_args.Req = req
	var _result inventory.InventoryServiceReserveStockResult
	if err = p.c.Call(ctx, "ReserveStock", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Biz != nil:
		return r, _result.Biz
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmDeduct(ctx context.Context, req *inventory.ConfirmDeductRequest) (r *common.Empty, err error) {
	var _args inventory.InventoryServiceConfirmDeductArgs
	_args.Req = req
	var _result inventory.InventoryServiceConfirmDeductResult
	if err = p.c.Call(ctx, "ConfirmDeduct", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Biz != nil:
		return r, _result.Biz
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseStock(ctx context.Context, req *inventory.ReleaseStockRequest) (r *common.Empty, err error) {
	var _args inventory.InventoryServiceReleaseStockArgs
	_args.Req = req
	var _result inventory.InventoryServiceReleaseStockResult
	if err = p.c.Call(ctx, "ReleaseStock", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Biz != nil:
		return r, _result.Biz
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReconcileStock(ctx context.Context, req *inventory.ReconcileStockRequest) (r *inventory.ReconcileStockResponse, err error) {
	var _args inventory.InventoryServiceReconcileStockArgs
	_args.Req = req
	var _result inventory.InventoryServiceReconcileStockResult
	if err = p.c.Call(ctx, "ReconcileStock", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Biz != nil:
		return r, _result.Biz
	}
	return _result.GetSuccess(), nil
}
