// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package inventory

import (
	"context"
	"flash-mall/app/inventory/kitex/kitex_gen/flashmall/common"
	"fmt"
)

type StockDTO struct {
	ProductId int64 `thrift:"product_id,1" frugal:"1,default,i64" json:"product_id"`
	Available int64 `thrift:"available,2" frugal:"2,default,i64" json:"available"`
	Reserved  int64 `thrift:"reserved,3" frugal:"3,default,i64" json:"reserved"`
	Total     int64 `thrift:"total,4" frugal:"4,default,i64" json:"total"`
}

func NewStockDTO() *StockDTO {
	return &StockDTO{}
}

func (p *StockDTO) InitDefault() {
}

func (p *StockDTO) GetProductId() (v int64) {
	return p.ProductId
}

func (p *StockDTO) GetAvailable() (v int64) {
	return p.Available
}

func (p *StockDTO) GetReserved() (v int64) {
	return p.Reserved
}

func (p *StockDTO) GetTotal() (v int64) {
	return p.Total
}
func (p *StockDTO) SetProductId(val int64) {
	p.ProductId = val
}
func (p *StockDTO) SetAvailable(val int64) {
	p.Available = val
}
func (p *StockDTO) SetReserved(val int64) {
	p.Reserved = val
}
func (p *StockDTO) SetTotal(val int64) {
	p.Total = val
}

func (p *StockDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockDTO(%+v)", *p)
}

var fieldIDToName_StockDTO = map[int16]string{
	1: "product_id",
	2: "available",
	3: "reserved",
	4: "total",
}

type GetStockRequest struct {
	Meta      *common.RequestMeta `thrift:"meta,1" frugal:"1,default,common.RequestMeta" json:"meta"`
	ProductId int64               `thrift:"product_id,2" frugal:"2,default,i64" json:"product_id"`
}

func NewGetStockRequest() *GetStockRequest {
	return &GetStockRequest{}
}

func (p *GetStockRequest) InitDefault() {
}

var GetStockRequest_Meta_DEFAULT *common.RequestMeta

func (p *GetStockRequest) GetMeta() (v *common.RequestMeta) {
	if !p.IsSetMeta() {
		return GetStockRequest_Meta_DEFAULT
	}
	return p.Meta
}

func (p *GetStockRequest) GetProductId() (v int64) {
	return p.ProductId
}
func (p *GetStockRequest) SetMeta(val *common.RequestMeta) {
	p.Meta = val
}
func (p *GetStockRequest) SetProductId(val int64) {
	p.ProductId = val
}

func (p *GetStockRequest) IsSetMeta() bool {
	return p.Meta != nil
}

func (p *GetStockRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetStockRequest(%+v)", *p)
}

var fieldIDToName_GetStockRequest = map[int16]string{
	1: "meta",
	2: "product_id",
}

type GetStockResponse struct {
	Stock *StockDTO `thrift:"stock,1" frugal:"1,default,StockDTO" json:"stock"`
}

func NewGetStockResponse() *GetStockResponse {
	return &GetStockResponse{}
}

func (p *GetStockResponse) InitDefault() {
}

var GetStockResponse_Stock_DEFAULT *StockDTO

func (p *GetStockResponse) GetStock() (v *StockDTO) {
	if !p.IsSetStock() {
		return GetStockResponse_Stock_DEFAULT
	}
	return p.Stock
}
func (p *GetStockResponse) SetStock(val *StockDTO) {
	p.Stock = val
}

func (p *GetStockResponse) IsSetStock() bool {
	return p.Stock != nil
}

func (p *GetStockResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetStockResponse(%+v)", *p)
}

var fieldIDToName_GetStockResponse = map[int16]string{
	1: "stock",
}

type SeedStockRequest struct {
	Meta       *common.RequestMeta `thrift:"meta,1" frugal:"1,default,common.RequestMeta" json:"meta"`
	ProductId  int64               `thrift:"product_id,2" frugal:"2,default,i64" json:"product_id"`
	Total      int64               `thrift:"total,3" frugal:"3,default,i64" json:"total"`
	ShardCount *int32              `thrift:"shard_count,4,optional" frugal:"4,optional,i32" json:"shard_count,omitempty"`
}

func NewSeedStockRequest() *SeedStockRequest {
	return &SeedStockRequest{}
}

func (p *SeedStockRequest) InitDefault() {
}

var SeedStockRequest_Meta_DEFAULT *common.RequestMeta

func (p *SeedStockRequest) GetMeta() (v *common.RequestMeta) {
	if !p.IsSetMeta() {
		return SeedStockRequest_Meta_DEFAULT
	}
	return p.Meta
}

func (p *SeedStockRequest) GetProductId() (v int64) {
	return p.ProductId
}

func (p *SeedStockRequest) GetTotal() (v int64) {
	return p.Total
}

var SeedStockRequest_ShardCount_DEFAULT int32

func (p *SeedStockRequest) GetShardCount() (v int32) {
	if !p.IsSetShardCount() {
		return SeedStockRequest_ShardCount_DEFAULT
	}
	return *p.ShardCount
}
func (p *SeedStockRequest) SetMeta(val *common.RequestMeta) {
	p.Meta = val
}
func (p *SeedStockRequest) SetProductId(val int64) {
	p.ProductId = val
}
func (p *SeedStockRequest) SetTotal(val int64) {
	p.Total = val
}
func (p *SeedStockRequest) SetShardCount(val *int32) {
	p.ShardCount = val
}

func (p *SeedStockRequest) IsSetMeta() bool {
	return p.Meta != nil
}

func (p *SeedStockRequest) IsSetShardCount() bool {
	return p.ShardCount != nil
}

func (p *SeedStockRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SeedStockRequest(%+v)", *p)
}

var fieldIDToName_SeedStockRequest = map[int16]string{
	1: "meta",
	2: "product_id",
	3: "total",
	4: "shard_count",
}

type ReserveStockRequest struct {
	Meta      *common.RequestMeta `thrift:"meta,1" frugal:"1,default,common.RequestMeta" json:"meta"`
	OrderId   string              `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	ProductId int64               `thrift:"product_id,3" frugal:"3,default,i64" json:"product_id"`
	Quantity  int64               `thrift:"quantity,4" frugal:"4,default,i64" json:"quantity"`
}

func NewReserveStockRequest() *ReserveStockRequest {
	return &ReserveStockRequest{}
}

func (p *ReserveStockRequest) InitDefault() {
}

var ReserveStockRequest_Meta_DEFAULT *common.RequestMeta

func (p *ReserveStockRequest) GetMeta() (v *common.RequestMeta) {
	if !p.IsSetMeta() {
		return ReserveStockRequest_Meta_DEFAULT
	}
	return p.Meta
}

func (p *ReserveStockRequest) GetOrderId() (v string) {
	return p.OrderId
}

func (p *ReserveStockRequest) GetProductId() (v int64) {
	return p.ProductId
}

func (p *ReserveStockRequest) GetQuantity() (v int64) {
	return p.Quantity
}
func (p *ReserveStockRequest) SetMeta(val *common.RequestMeta) {
	p.Meta = val
}
func (p *ReserveStockRequest) SetOrderId(val string) {
	p.OrderId = val
}
func (p *ReserveStockRequest) SetProductId(val int64) {
	p.ProductId = val
}
func (p *ReserveStockRequest) SetQuantity(val int64) {
	p.Quantity = val
}

func (p *ReserveStockRequest) IsSetMeta() bool {
	return p.Meta != nil
}

func (p *ReserveStockRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReserveStockRequest(%+v)", *p)
}

var fieldIDToName_ReserveStockRequest = map[int16]string{
	1: "meta",
	2: "order_id",
	3: "product_id",
	4: "quantity",
}

type ConfirmDeductRequest struct {
	Meta    *common.RequestMeta `thrift:"meta,1" frugal:"1,default,common.RequestMeta" json:"meta"`
	OrderId string              `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
}

func NewConfirmDeductRequest() *ConfirmDeductRequest {
	return &ConfirmDeductRequest{}
}

func (p *ConfirmDeductRequest) InitDefault() {
}

var ConfirmDeductRequest_Meta_DEFAULT *common.RequestMeta

func (p *ConfirmDeductRequest) GetMeta() (v *common.RequestMeta) {
	if !p.IsSetMeta() {
		return ConfirmDeductRequest_Meta_DEFAULT
	}
	return p.Meta
}

func (p *ConfirmDeductRequest) GetOrderId() (v string) {
	return p.OrderId
}
func (p *ConfirmDeductRequest) SetMeta(val *common.RequestMeta) {
	p.Meta = val
}
func (p *ConfirmDeductRequest) SetOrderId(val string) {
	p.OrderId = val
}

func (p *ConfirmDeductRequest) IsSetMeta() bool {
	return p.Meta != nil
}

func (p *ConfirmDeductRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmDeductRequest(%+v)", *p)
}

var fieldIDToName_ConfirmDeductRequest = map[int16]string{
	1: "meta",
	2: "order_id",
}

type ReleaseStockRequest struct {
	Meta    *common.RequestMeta `thrift:"meta,1" frugal:"1,default,common.RequestMeta" json:"meta"`
	OrderId string              `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	Reason  *string             `thrift:"reason,3,optional" frugal:"3,optional,string" json:"reason,omitempty"`
}

func NewReleaseStockRequest() *ReleaseStockRequest {
	return &ReleaseStockRequest{}
}

func (p *ReleaseStockRequest) InitDefault() {
}

var ReleaseStockRequest_Meta_DEFAULT *common.RequestMeta

func (p *ReleaseStockRequest) GetMeta() (v *common.RequestMeta) {
	if !p.IsSetMeta() {
		return ReleaseStockRequest_Meta_DEFAULT
	}
	return p.Meta
}

func (p *ReleaseStockRequest) GetOrderId() (v string) {
	return p.OrderId
}

var ReleaseStockRequest_Reason_DEFAULT string

func (p *ReleaseStockRequest) GetReason() (v string) {
	if !p.IsSetReason() {
		return ReleaseStockRequest_Reason_DEFAULT
	}
	return *p.Reason
}
func (p *ReleaseStockRequest) SetMeta(val *common.RequestMeta) {
	p.Meta = val
}
func (p *ReleaseStockRequest) SetOrderId(val string) {
	p.OrderId = val
}
func (p *ReleaseStockRequest) SetReason(val *string) {
	p.Reason = val
}

func (p *ReleaseStockRequest) IsSetMeta() bool {
	return p.Meta != nil
}

func (p *ReleaseStockRequest) IsSetReason() bool {
	return p.Reason != nil
}

func (p *ReleaseStockRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseStockRequest(%+v)", *p)
}

var fieldIDToName_ReleaseStockRequest = map[int16]string{
	1: "meta",
	2: "order_id",
	3: "reason",
}

type ReconcileStockRequest struct {
	Meta      *common.RequestMeta `thrift:"meta,1" frugal:"1,default,common.RequestMeta" json:"meta"`
	ProductId int64               `thrift:"product_id,2" frugal:"2,default,i64" json:"product_id"`
}

func NewReconcileStockRequest() *ReconcileStockRequest {
	return &ReconcileStockRequest{}
}

func (p *ReconcileStockRequest) InitDefault() {
}

var ReconcileStockRequest_Meta_DEFAULT *common.RequestMeta

func (p *ReconcileStockRequest) GetMeta() (v *common.RequestMeta) {
	if !p.IsSetMeta() {
		return ReconcileStockRequest_Meta_DEFAULT
	}
	return p.Meta
}

func (p *ReconcileStockRequest) GetProductId() (v int64) {
	return p.ProductId
}
func (p *ReconcileStockRequest) SetMeta(val *common.RequestMeta) {
	p.Meta = val
}
func (p *ReconcileStockRequest) SetProductId(val int64) {
	p.ProductId = val
}

func (p *ReconcileStockRequest) IsSetMeta() bool {
	return p.Meta != nil
}

func (p *ReconcileStockRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReconcileStockRequest(%+v)", *p)
}

var fieldIDToName_ReconcileStockRequest = map[int16]string{
	1: "meta",
	2: "product_id",
}

type ReconcileStockResponse struct {
	Before  *StockDTO `thrift:"before,1" frugal:"1,default,StockDTO" json:"before"`
	After   *StockDTO `thrift:"after,2" frugal:"2,default,StockDTO" json:"after"`
	Changed bool      `thrift:"changed,3" frugal:"3,default,bool" json:"changed"`
}

func NewReconcileStockResponse() *ReconcileStockResponse {
	return &ReconcileStockResponse{}
}

func (p *ReconcileStockResponse) InitDefault() {
}

var ReconcileStockResponse_Before_DEFAULT *StockDTO

func (p *ReconcileStockResponse) GetBefore() (v *StockDTO) {
	if !p.IsSetBefore() {
		return ReconcileStockResponse_Before_DEFAULT
	}
	return p.Before
}

var ReconcileStockResponse_After_DEFAULT *StockDTO

func (p *ReconcileStockResponse) GetAfter() (v *StockDTO) {
	if !p.IsSetAfter() {
		return ReconcileStockResponse_After_DEFAULT
	}
	return p.After
}

func (p *ReconcileStockResponse) GetChanged() (v bool) {
	return p.Changed
}
func (p *ReconcileStockResponse) SetBefore(val *StockDTO) {
	p.Before = val
}
func (p *ReconcileStockResponse) SetAfter(val *StockDTO) {
	p.After = val
}
func (p *ReconcileStockResponse) SetChanged(val bool) {
	p.Changed = val
}

func (p *ReconcileStockResponse) IsSetBefore() bool {
	return p.Before != nil
}

func (p *ReconcileStockResponse) IsSetAfter() bool {
	return p.After != nil
}

func (p *ReconcileStockResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReconcileStockResponse(%+v)", *p)
}

var fieldIDToName_ReconcileStockResponse = map[int16]string{
	1: "before",
	2: "after",
	3: "changed",
}

type InventoryService interface {
	GetStock(ctx context.Context, req *GetStockRequest) (r *GetStockResponse, err error)

	SeedStock(ctx context.Context, req *SeedStockRequest) (r *common.Empty, err error)

	ReserveStock(ctx context.Context, req *ReserveStockRequest) (r *common.Empty, err error)

	ConfirmDeduct(ctx context.Context, req *ConfirmDeductRequest) (r *common.Empty, err error)

	ReleaseStock(ctx context.Context, req *ReleaseStockRequest) (r *common.Empty, err error)

	ReconcileStock(ctx context.Context, req *ReconcileStockRequest) (r *ReconcileStockResponse, err error)
}

type InventoryServiceGetStockArgs struct {
	Req *GetStockRequest `thrift:"req,1" frugal:"1,default,GetStockRequest" json:"req"`
}

func NewInventoryServiceGetStockArgs() *InventoryServiceGetStockArgs {
	return &InventoryServiceGetStockArgs{}
}

func (p *InventoryServiceGetStockArgs) InitDefault() {
}

var InventoryServiceGetStockArgs_Req_DEFAULT *GetStockRequest

func (p *InventoryServiceGetStockArgs) GetReq() (v *GetStockRequest) {
	if !p.IsSetReq() {
		return InventoryServiceGetStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InventoryServiceGetStockArgs) SetReq(val *GetStockRequest) {
	p.Req = val
}

func (p *InventoryServiceGetStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InventoryServiceGetStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceGetStockArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceGetStockArgs = map[int16]string{
	1: "req",
}

type InventoryServiceGetStockResult struct {
	Success *GetStockResponse    `thrift:"success,0,optional" frugal:"0,optional,GetStockResponse" json:"success,omitempty"`
	Biz     *common.BizException `thrift:"biz,1,optional" frugal:"1,optional,common.BizException" json:"biz,omitempty"`
}

func NewInventoryServiceGetStockResult() *InventoryServiceGetStockResult {
	return &InventoryServiceGetStockResult{}
}

func (p *InventoryServiceGetStockResult) InitDefault() {
}

var InventoryServiceGetStockResult_Success_DEFAULT *GetStockResponse

func (p *InventoryServiceGetStockResult) GetSuccess() (v *GetStockResponse) {
	if !p.IsSetSuccess() {
		return InventoryServiceGetStockResult_Success_DEFAULT
	}
	return p.Success
}

var InventoryServiceGetStockResult_Biz_DEFAULT *common.BizException

func (p *InventoryServiceGetStockResult) GetBiz() (v *common.BizException) {
	if !p.IsSetBiz() {
		return InventoryServiceGetStockResult_Biz_DEFAULT
	}
	return p.Biz
}
func (p *InventoryServiceGetStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetStockResponse)
}
func (p *InventoryServiceGetStockResult) SetBiz(val *common.BizException) {
	p.Biz = val
}

func (p *InventoryServiceGetStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceGetStockResult) IsSetBiz() bool {
	return p.Biz != nil
}

func (p *InventoryServiceGetStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceGetStockResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceGetStockResult = map[int16]string{
	0: "success",
	1: "biz",
}

type InventoryServiceSeedStockArgs struct {
	Req *SeedStockRequest `thrift:"req,1" frugal:"1,default,SeedStockRequest" json:"req"`
}

func NewInventoryServiceSeedStockArgs() *InventoryServiceSeedStockArgs {
	return &InventoryServiceSeedStockArgs{}
}

func (p *InventoryServiceSeedStockArgs) InitDefault() {
}

var InventoryServiceSeedStockArgs_Req_DEFAULT *SeedStockRequest

func (p *InventoryServiceSeedStockArgs) GetReq() (v *SeedStockRequest) {
	if !p.IsSetReq() {
		return InventoryServiceSeedStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InventoryServiceSeedStockArgs) SetReq(val *SeedStockRequest) {
	p.Req = val
}

func (p *InventoryServiceSeedStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InventoryServiceSeedStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceSeedStockArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceSeedStockArgs = map[int16]string{
	1: "req",
}

type InventoryServiceSeedStockResult struct {
	Success *common.Empty        `thrift:"success,0,optional" frugal:"0,optional,common.Empty" json:"success,omitempty"`
	Biz     *common.BizException `thrift:"biz,1,optional" frugal:"1,optional,common.BizException" json:"biz,omitempty"`
}

func NewInventoryServiceSeedStockResult() *InventoryServiceSeedStockResult {
	return &InventoryServiceSeedStockResult{}
}

func (p *InventoryServiceSeedStockResult) InitDefault() {
}

var InventoryServiceSeedStockResult_Success_DEFAULT *common.Empty

func (p *InventoryServiceSeedStockResult) GetSuccess() (v *common.Empty) {
	if !p.IsSetSuccess() {
		return InventoryServiceSeedStockResult_Success_DEFAULT
	}
	return p.Success
}

var InventoryServiceSeedStockResult_Biz_DEFAULT *common.BizException

func (p *InventoryServiceSeedStockResult) GetBiz() (v *common.BizException) {
	if !p.IsSetBiz() {
		return InventoryServiceSeedStockResult_Biz_DEFAULT
	}
	return p.Biz
}
func (p *InventoryServiceSeedStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.Empty)
}
func (p *InventoryServiceSeedStockResult) SetBiz(val *common.BizException) {
	p.Biz = val
}

func (p *InventoryServiceSeedStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceSeedStockResult) IsSetBiz() bool {
	return p.Biz != nil
}

func (p *InventoryServiceSeedStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceSeedStockResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceSeedStockResult = map[int16]string{
	0: "success",
	1: "biz",
}

type InventoryServiceReserveStockArgs struct {
	Req *ReserveStockRequest `thrift:"req,1" frugal:"1,default,ReserveStockRequest" json:"req"`
}

func NewInventoryServiceReserveStockArgs() *InventoryServiceReserveStockArgs {
	return &InventoryServiceReserveStockArgs{}
}

func (p *InventoryServiceReserveStockArgs) InitDefault() {
}

var InventoryServiceReserveStockArgs_Req_DEFAULT *ReserveStockRequest

func (p *InventoryServiceReserveStockArgs) GetReq() (v *ReserveStockRequest) {
	if !p.IsSetReq() {
		return InventoryServiceReserveStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InventoryServiceReserveStockArgs) SetReq(val *ReserveStockRequest) {
	p.Req = val
}

func (p *InventoryServiceReserveStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InventoryServiceReserveStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceReserveStockArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceReserveStockArgs = map[int16]string{
	1: "req",
}

type InventoryServiceReserveStockResult struct {
	Success *common.Empty        `thrift:"success,0,optional" frugal:"0,optional,common.Empty" json:"success,omitempty"`
	Biz     *common.BizException `thrift:"biz,1,optional" frugal:"1,optional,common.BizException" json:"biz,omitempty"`
}

func NewInventoryServiceReserveStockResult() *InventoryServiceReserveStockResult {
	return &InventoryServiceReserveStockResult{}
}

func (p *InventoryServiceReserveStockResult) InitDefault() {
}

var InventoryServiceReserveStockResult_Success_DEFAULT *common.Empty

func (p *InventoryServiceReserveStockResult) GetSuccess() (v *common.Empty) {
	if !p.IsSetSuccess() {
		return InventoryServiceReserveStockResult_Success_DEFAULT
	}
	return p.Success
}

var InventoryServiceReserveStockResult_Biz_DEFAULT *common.BizException

func (p *InventoryServiceReserveStockResult) GetBiz() (v *common.BizException) {
	if !p.IsSetBiz() {
		return InventoryServiceReserveStockResult_Biz_DEFAULT
	}
	return p.Biz
}
func (p *InventoryServiceReserveStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.Empty)
}
func (p *InventoryServiceReserveStockResult) SetBiz(val *common.BizException) {
	p.Biz = val
}

func (p *InventoryServiceReserveStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceReserveStockResult) IsSetBiz() bool {
	return p.Biz != nil
}

func (p *InventoryServiceReserveStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceReserveStockResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceReserveStockResult = map[int16]string{
	0: "success",
	1: "biz",
}

type InventoryServiceConfirmDeductArgs struct {
	Req *ConfirmDeductRequest `thrift:"req,1" frugal:"1,default,ConfirmDeductRequest" json:"req"`
}

func NewInventoryServiceConfirmDeductArgs() *InventoryServiceConfirmDeductArgs {
	return &InventoryServiceConfirmDeductArgs{}
}

func (p *InventoryServiceConfirmDeductArgs) InitDefault() {
}

var InventoryServiceConfirmDeductArgs_Req_DEFAULT *ConfirmDeductRequest

func (p *InventoryServiceConfirmDeductArgs) GetReq() (v *ConfirmDeductRequest) {
	if !p.IsSetReq() {
		return InventoryServiceConfirmDeductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InventoryServiceConfirmDeductArgs) SetReq(val *ConfirmDeductRequest) {
	p.Req = val
}

func (p *InventoryServiceConfirmDeductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InventoryServiceConfirmDeductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceConfirmDeductArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceConfirmDeductArgs = map[int16]string{
	1: "req",
}

type InventoryServiceConfirmDeductResult struct {
	Success *common.Empty        `thrift:"success,0,optional" frugal:"0,optional,common.Empty" json:"success,omitempty"`
	Biz     *common.BizException `thrift:"biz,1,optional" frugal:"1,optional,common.BizException" json:"biz,omitempty"`
}

func NewInventoryServiceConfirmDeductResult() *InventoryServiceConfirmDeductResult {
	return &InventoryServiceConfirmDeductResult{}
}

func (p *InventoryServiceConfirmDeductResult) InitDefault() {
}

var InventoryServiceConfirmDeductResult_Success_DEFAULT *common.Empty

func (p *InventoryServiceConfirmDeductResult) GetSuccess() (v *common.Empty) {
	if !p.IsSetSuccess() {
		return InventoryServiceConfirmDeductResult_Success_DEFAULT
	}
	return p.Success
}

var InventoryServiceConfirmDeductResult_Biz_DEFAULT *common.BizException

func (p *InventoryServiceConfirmDeductResult) GetBiz() (v *common.BizException) {
	if !p.IsSetBiz() {
		return InventoryServiceConfirmDeductResult_Biz_DEFAULT
	}
	return p.Biz
}
func (p *InventoryServiceConfirmDeductResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.Empty)
}
func (p *InventoryServiceConfirmDeductResult) SetBiz(val *common.BizException) {
	p.Biz = val
}

func (p *InventoryServiceConfirmDeductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceConfirmDeductResult) IsSetBiz() bool {
	return p.Biz != nil
}

func (p *InventoryServiceConfirmDeductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceConfirmDeductResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceConfirmDeductResult = map[int16]string{
	0: "success",
	1: "biz",
}

type InventoryServiceReleaseStockArgs struct {
	Req *ReleaseStockRequest `thrift:"req,1" frugal:"1,default,ReleaseStockRequest" json:"req"`
}

func NewInventoryServiceReleaseStockArgs() *InventoryServiceReleaseStockArgs {
	return &InventoryServiceReleaseStockArgs{}
}

func (p *InventoryServiceReleaseStockArgs) InitDefault() {
}

var InventoryServiceReleaseStockArgs_Req_DEFAULT *ReleaseStockRequest

func (p *InventoryServiceReleaseStockArgs) GetReq() (v *ReleaseStockRequest) {
	if !p.IsSetReq() {
		return InventoryServiceReleaseStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InventoryServiceReleaseStockArgs) SetReq(val *ReleaseStockRequest) {
	p.Req = val
}

func (p *InventoryServiceReleaseStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InventoryServiceReleaseStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceReleaseStockArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceReleaseStockArgs = map[int16]string{
	1: "req",
}

type InventoryServiceReleaseStockResult struct {
	Success *common.Empty        `thrift:"success,0,optional" frugal:"0,optional,common.Empty" json:"success,omitempty"`
	Biz     *common.BizException `thrift:"biz,1,optional" frugal:"1,optional,common.BizException" json:"biz,omitempty"`
}

func NewInventoryServiceReleaseStockResult() *InventoryServiceReleaseStockResult {
	return &InventoryServiceReleaseStockResult{}
}

func (p *InventoryServiceReleaseStockResult) InitDefault() {
}

var InventoryServiceReleaseStockResult_Success_DEFAULT *common.Empty

func (p *InventoryServiceReleaseStockResult) GetSuccess() (v *common.Empty) {
	if !p.IsSetSuccess() {
		return InventoryServiceReleaseStockResult_Success_DEFAULT
	}
	return p.Success
}

var InventoryServiceReleaseStockResult_Biz_DEFAULT *common.BizException

func (p *InventoryServiceReleaseStockResult) GetBiz() (v *common.BizException) {
	if !p.IsSetBiz() {
		return InventoryServiceReleaseStockResult_Biz_DEFAULT
	}
	return p.Biz
}
func (p *InventoryServiceReleaseStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.Empty)
}
func (p *InventoryServiceReleaseStockResult) SetBiz(val *common.BizException) {
	p.Biz = val
}

func (p *InventoryServiceReleaseStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceReleaseStockResult) IsSetBiz() bool {
	return p.Biz != nil
}

func (p *InventoryServiceReleaseStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceReleaseStockResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceReleaseStockResult = map[int16]string{
	0: "success",
	1: "biz",
}

type InventoryServiceReconcileStockArgs struct {
	Req *ReconcileStockRequest `thrift:"req,1" frugal:"1,default,ReconcileStockRequest" json:"req"`
}

func NewInventoryServiceReconcileStockArgs() *InventoryServiceReconcileStockArgs {
	return &InventoryServiceReconcileStockArgs{}
}

func (p *InventoryServiceReconcileStockArgs) InitDefault() {
}

var InventoryServiceReconcileStockArgs_Req_DEFAULT *ReconcileStockRequest

func (p *InventoryServiceReconcileStockArgs) GetReq() (v *ReconcileStockRequest) {
	if !p.IsSetReq() {
		return InventoryServiceReconcileStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InventoryServiceReconcileStockArgs) SetReq(val *ReconcileStockRequest) {
	p.Req = val
}

func (p *InventoryServiceReconcileStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InventoryServiceReconcileStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceReconcileStockArgs(%+v)", *p)
}

var fieldIDToName_InventoryServiceReconcileStockArgs = map[int16]string{
	1: "req",
}

type InventoryServiceReconcileStockResult struct {
	Success *ReconcileStockResponse `thrift:"success,0,optional" frugal:"0,optional,ReconcileStockResponse" json:"success,omitempty"`
	Biz     *common.BizException    `thrift:"biz,1,optional" frugal:"1,optional,common.BizException" json:"biz,omitempty"`
}

func NewInventoryServiceReconcileStockResult() *InventoryServiceReconcileStockResult {
	return &InventoryServiceReconcileStockResult{}
}

func (p *InventoryServiceReconcileStockResult) InitDefault() {
}

var InventoryServiceReconcileStockResult_Success_DEFAULT *ReconcileStockResponse

func (p *InventoryServiceReconcileStockResult) GetSuccess() (v *ReconcileStockResponse) {
	if !p.IsSetSuccess() {
		return InventoryServiceReconcileStockResult_Success_DEFAULT
	}
	return p.Success
}

var InventoryServiceReconcileStockResult_Biz_DEFAULT *common.BizException

func (p *InventoryServiceReconcileStockResult) GetBiz() (v *common.BizException) {
	if !p.IsSetBiz() {
		return InventoryServiceReconcileStockResult_Biz_DEFAULT
	}
	return p.Biz
}
func (p *InventoryServiceReconcileStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*ReconcileStockResponse)
}
func (p *InventoryServiceReconcileStockResult) SetBiz(val *common.BizException) {
	p.Biz = val
}

func (p *InventoryServiceReconcileStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InventoryServiceReconcileStockResult) IsSetBiz() bool {
	return p.Biz != nil
}

func (p *InventoryServiceReconcileStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InventoryServiceReconcileStockResult(%+v)", *p)
}

var fieldIDToName_InventoryServiceReconcileStockResult = map[int16]string{
	0: "success",
	1: "biz",
}

// exceptions of methods in InventoryService.
var (
	_ error = (*common.BizException)(nil)
)
