// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeductReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num   int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	// CHG 2026-02-24: 变更=新增 order_id; 之前=扣减请求无幂等键; 原因=库存分桶与回滚需要定位桶。
	OrderId       string `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductReq) Reset() {
	*x = DeductReq{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductReq) ProtoMessage() {}

func (x *DeductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductReq.ProtoReflect.Descriptor instead.
func (*DeductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *DeductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeductReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *DeductReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

type GetProductCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCardReq) Reset() {
	*x = GetProductCardReq{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCardReq) ProtoMessage() {}

func (x *GetProductCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCardReq.ProtoReflect.Descriptor instead.
func (*GetProductCardReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductCardReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductCardResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OriginPriceFen int64                  `protobuf:"varint,3,opt,name=origin_price_fen,json=originPriceFen,proto3" json:"origin_price_fen,omitempty"`
	FinalPriceFen  int64                  `protobuf:"varint,4,opt,name=final_price_fen,json=finalPriceFen,proto3" json:"final_price_fen,omitempty"`
	PromotionType  string                 `protobuf:"bytes,5,opt,name=promotion_type,json=promotionType,proto3" json:"promotion_type,omitempty"`
	PromotionTag   string                 `protobuf:"bytes,6,opt,name=promotion_tag,json=promotionTag,proto3" json:"promotion_tag,omitempty"`
	StockAvailable int64                  `protobuf:"varint,7,opt,name=stock_available,json=stockAvailable,proto3" json:"stock_available,omitempty"`
	SupplierId     int64                  `protobuf:"varint,8,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	MerchantId     int64                  `protobuf:"varint,10,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProductCardResp) Reset() {
	*x = GetProductCardResp{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCardResp) ProtoMessage() {}

func (x *GetProductCardResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCardResp.ProtoReflect.Descriptor instead.
func (*GetProductCardResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductCardResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetProductCardResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductCardResp) GetOriginPriceFen() int64 {
	if x != nil {
		return x.OriginPriceFen
	}
	return 0
}

func (x *GetProductCardResp) GetFinalPriceFen() int64 {
	if x != nil {
		return x.FinalPriceFen
	}
	return 0
}

func (x *GetProductCardResp) GetPromotionType() string {
	if x != nil {
		return x.PromotionType
	}
	return ""
}

func (x *GetProductCardResp) GetPromotionTag() string {
	if x != nil {
		return x.PromotionTag
	}
	return ""
}

func (x *GetProductCardResp) GetStockAvailable() int64 {
	if x != nil {
		return x.StockAvailable
	}
	return 0
}

func (x *GetProductCardResp) GetSupplierId() int64 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

func (x *GetProductCardResp) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GetProductCardResp) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type RevertStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertStockReq) Reset() {
	*x = RevertStockReq{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertStockReq) ProtoMessage() {}

func (x *RevertStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertStockReq.ProtoReflect.Descriptor instead.
func (*RevertStockReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *RevertStockReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RevertStockReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *RevertStockReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type RevertStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertStockResp) Reset() {
	*x = RevertStockResp{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertStockResp) ProtoMessage() {}

func (x *RevertStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertStockResp.ProtoReflect.Descriptor instead.
func (*RevertStockResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

type ListProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []int64                `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNum       int64                  `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	StatusFilter  int32                  `protobuf:"varint,4,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // 0=all, 1=active only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReq) Reset() {
	*x = ListProductsReq{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReq) ProtoMessage() {}

func (x *ListProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReq.ProtoReflect.Descriptor instead.
func (*ListProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsReq) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *ListProductsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListProductsReq) GetStatusFilter() int32 {
	if x != nil {
		return x.StatusFilter
	}
	return 0
}

type ListProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetProductCardResp  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResp) Reset() {
	*x = ListProductsResp{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResp) ProtoMessage() {}

func (x *ListProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResp.ProtoReflect.Descriptor instead.
func (*ListProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResp) GetItems() []*GetProductCardResp {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProductsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\"H\n" +
	"\tDeductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"\a\n" +
	"\x05Empty\"2\n" +
	"\x11GetProductCardReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"\xed\x02\n" +
	"\x12GetProductCardResp\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x10origin_price_fen\x18\x03 \x01(\x03R\x0eoriginPriceFen\x12&\n" +
	"\x0ffinal_price_fen\x18\x04 \x01(\x03R\rfinalPriceFen\x12%\n" +
	"\x0epromotion_type\x18\x05 \x01(\tR\rpromotionType\x12#\n" +
	"\rpromotion_tag\x18\x06 \x01(\tR\fpromotionTag\x12'\n" +
	"\x0fstock_available\x18\a \x01(\x03R\x0estockAvailable\x12\x1f\n" +
	"\vsupplier_id\x18\b \x01(\x03R\n" +
	"supplierId\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vmerchant_id\x18\n" +
	" \x01(\x03R\n" +
	"merchantId\"M\n" +
	"\x0eRevertStockReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"\x11\n" +
	"\x0fRevertStockResp\"\x8f\x01\n" +
	"\x0fListProductsReq\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x03R\n" +
	"productIds\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x19\n" +
	"\bpage_num\x18\x03 \x01(\x03R\apageNum\x12#\n" +
	"\rstatus_filter\x18\x04 \x01(\x05R\fstatusFilter\"[\n" +
	"\x10ListProductsResp\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.product.GetProductCardRespR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xbf\x02\n" +
	"\aProduct\x12I\n" +
	"\x0eGetProductCard\x12\x1a.product.GetProductCardReq\x1a\x1b.product.GetProductCardResp\x12C\n" +
	"\fListProducts\x12\x18.product.ListProductsReq\x1a\x19.product.ListProductsResp\x12,\n" +
	"\x06Deduct\x12\x12.product.DeductReq\x1a\x0e.product.Empty\x124\n" +
	"\x0eDeductRollback\x12\x12.product.DeductReq\x1a\x0e.product.Empty\x12@\n" +
	"\vRevertStock\x12\x17.product.RevertStockReq\x1a\x18.product.RevertStockRespB\vZ\t./productb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_product_proto_goTypes = []any{
	(*DeductReq)(nil),          // 0: product.DeductReq
	(*Empty)(nil),              // 1: product.Empty
	(*GetProductCardReq)(nil),  // 2: product.GetProductCardReq
	(*GetProductCardResp)(nil), // 3: product.GetProductCardResp
	(*RevertStockReq)(nil),     // 4: product.RevertStockReq
	(*RevertStockResp)(nil),    // 5: product.RevertStockResp
	(*ListProductsReq)(nil),    // 6: product.ListProductsReq
	(*ListProductsResp)(nil),   // 7: product.ListProductsResp
}
var file_product_proto_depIdxs = []int32{
	3, // 0: product.ListProductsResp.items:type_name -> product.GetProductCardResp
	2, // 1: product.Product.GetProductCard:input_type -> product.GetProductCardReq
	6, // 2: product.Product.ListProducts:input_type -> product.ListProductsReq
	0, // 3: product.Product.Deduct:input_type -> product.DeductReq
	0, // 4: product.Product.DeductRollback:input_type -> product.DeductReq
	4, // 5: product.Product.RevertStock:input_type -> product.RevertStockReq
	3, // 6: product.Product.GetProductCard:output_type -> product.GetProductCardResp
	7, // 7: product.Product.ListProducts:output_type -> product.ListProductsResp
	1, // 8: product.Product.Deduct:output_type -> product.Empty
	1, // 9: product.Product.DeductRollback:output_type -> product.Empty
	5, // 10: product.Product.RevertStock:output_type -> product.RevertStockResp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
