// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: app/order/rpc/order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Order_PreDeduct_FullMethodName           = "/order.Order/PreDeduct"
	Order_PreDeductRollback_FullMethodName   = "/order.Order/PreDeductRollback"
	Order_CreateOrder_FullMethodName         = "/order.Order/CreateOrder"
	Order_CreateOrderRollback_FullMethodName = "/order.Order/CreateOrderRollback"
	Order_MarkOrderPaid_FullMethodName       = "/order.Order/MarkOrderPaid"
	Order_GetOrderDetail_FullMethodName      = "/order.Order/GetOrderDetail"
	Order_RequestRefund_FullMethodName       = "/order.Order/RequestRefund"
	Order_AuditRefund_FullMethodName         = "/order.Order/AuditRefund"
	Order_CancelUserOrder_FullMethodName     = "/order.Order/CancelUserOrder"
	Order_CloseAdminOrder_FullMethodName     = "/order.Order/CloseAdminOrder"
	Order_ShipAdminOrder_FullMethodName      = "/order.Order/ShipAdminOrder"
	Order_ShipMerchantOrder_FullMethodName   = "/order.Order/ShipMerchantOrder"
	Order_ConfirmReceipt_FullMethodName      = "/order.Order/ConfirmReceipt"
)

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderClient interface {
	// Redis 预扣库存（正向）
	PreDeduct(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error)
	// Redis 预扣回滚（补偿）
	PreDeductRollback(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error)
	// 创建订单（正向）
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
	// 订单回滚/关闭（补偿）
	CreateOrderRollback(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*Empty, error)
	MarkOrderPaid(ctx context.Context, in *MarkOrderPaidReq, opts ...grpc.CallOption) (*MarkOrderPaidResp, error)
	GetOrderDetail(ctx context.Context, in *GetOrderDetailReq, opts ...grpc.CallOption) (*GetOrderDetailResp, error)
	RequestRefund(ctx context.Context, in *RequestRefundReq, opts ...grpc.CallOption) (*RequestRefundResp, error)
	AuditRefund(ctx context.Context, in *AuditRefundReq, opts ...grpc.CallOption) (*AuditRefundResp, error)
	// 用户取消待支付订单；重复调用仍会重试幂等库存释放。
	CancelUserOrder(ctx context.Context, in *CancelUserOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
	// 管理员关闭待支付订单；重复调用仍会重试幂等库存释放。
	CloseAdminOrder(ctx context.Context, in *CloseAdminOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
	ShipAdminOrder(ctx context.Context, in *ShipAdminOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
	ShipMerchantOrder(ctx context.Context, in *ShipMerchantOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
	ConfirmReceipt(ctx context.Context, in *ConfirmReceiptReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) PreDeduct(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Order_PreDeduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) PreDeductRollback(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Order_PreDeductRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResp)
	err := c.cc.Invoke(ctx, Order_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrderRollback(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Order_CreateOrderRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) MarkOrderPaid(ctx context.Context, in *MarkOrderPaidReq, opts ...grpc.CallOption) (*MarkOrderPaidResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkOrderPaidResp)
	err := c.cc.Invoke(ctx, Order_MarkOrderPaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrderDetail(ctx context.Context, in *GetOrderDetailReq, opts ...grpc.CallOption) (*GetOrderDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderDetailResp)
	err := c.cc.Invoke(ctx, Order_GetOrderDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) RequestRefund(ctx context.Context, in *RequestRefundReq, opts ...grpc.CallOption) (*RequestRefundResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestRefundResp)
	err := c.cc.Invoke(ctx, Order_RequestRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) AuditRefund(ctx context.Context, in *AuditRefundReq, opts ...grpc.CallOption) (*AuditRefundResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditRefundResp)
	err := c.cc.Invoke(ctx, Order_AuditRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CancelUserOrder(ctx context.Context, in *CancelUserOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderCommandResp)
	err := c.cc.Invoke(ctx, Order_CancelUserOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CloseAdminOrder(ctx context.Context, in *CloseAdminOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderCommandResp)
	err := c.cc.Invoke(ctx, Order_CloseAdminOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ShipAdminOrder(ctx context.Context, in *ShipAdminOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderCommandResp)
	err := c.cc.Invoke(ctx, Order_ShipAdminOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ShipMerchantOrder(ctx context.Context, in *ShipMerchantOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderCommandResp)
	err := c.cc.Invoke(ctx, Order_ShipMerchantOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) ConfirmReceipt(ctx context.Context, in *ConfirmReceiptReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderCommandResp)
	err := c.cc.Invoke(ctx, Order_ConfirmReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility.
type OrderServer interface {
	// Redis 预扣库存（正向）
	PreDeduct(context.Context, *PreDeductReq) (*Empty, error)
	// Redis 预扣回滚（补偿）
	PreDeductRollback(context.Context, *PreDeductReq) (*Empty, error)
	// 创建订单（正向）
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error)
	// 订单回滚/关闭（补偿）
	CreateOrderRollback(context.Context, *CreateOrderReq) (*Empty, error)
	MarkOrderPaid(context.Context, *MarkOrderPaidReq) (*MarkOrderPaidResp, error)
	GetOrderDetail(context.Context, *GetOrderDetailReq) (*GetOrderDetailResp, error)
	RequestRefund(context.Context, *RequestRefundReq) (*RequestRefundResp, error)
	AuditRefund(context.Context, *AuditRefundReq) (*AuditRefundResp, error)
	// 用户取消待支付订单；重复调用仍会重试幂等库存释放。
	CancelUserOrder(context.Context, *CancelUserOrderReq) (*OrderCommandResp, error)
	// 管理员关闭待支付订单；重复调用仍会重试幂等库存释放。
	CloseAdminOrder(context.Context, *CloseAdminOrderReq) (*OrderCommandResp, error)
	ShipAdminOrder(context.Context, *ShipAdminOrderReq) (*OrderCommandResp, error)
	ShipMerchantOrder(context.Context, *ShipMerchantOrderReq) (*OrderCommandResp, error)
	ConfirmReceipt(context.Context, *ConfirmReceiptReq) (*OrderCommandResp, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServer struct{}

func (UnimplementedOrderServer) PreDeduct(context.Context, *PreDeductReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreDeduct not implemented")
}
func (UnimplementedOrderServer) PreDeductRollback(context.Context, *PreDeductReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreDeductRollback not implemented")
}
func (UnimplementedOrderServer) CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServer) CreateOrderRollback(context.Context, *CreateOrderReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderRollback not implemented")
}
func (UnimplementedOrderServer) MarkOrderPaid(context.Context, *MarkOrderPaidReq) (*MarkOrderPaidResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkOrderPaid not implemented")
}
func (UnimplementedOrderServer) GetOrderDetail(context.Context, *GetOrderDetailReq) (*GetOrderDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderDetail not implemented")
}
func (UnimplementedOrderServer) RequestRefund(context.Context, *RequestRefundReq) (*RequestRefundResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRefund not implemented")
}
func (UnimplementedOrderServer) AuditRefund(context.Context, *AuditRefundReq) (*AuditRefundResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditRefund not implemented")
}
func (UnimplementedOrderServer) CancelUserOrder(context.Context, *CancelUserOrderReq) (*OrderCommandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelUserOrder not implemented")
}
func (UnimplementedOrderServer) CloseAdminOrder(context.Context, *CloseAdminOrderReq) (*OrderCommandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseAdminOrder not implemented")
}
func (UnimplementedOrderServer) ShipAdminOrder(context.Context, *ShipAdminOrderReq) (*OrderCommandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShipAdminOrder not implemented")
}
func (UnimplementedOrderServer) ShipMerchantOrder(context.Context, *ShipMerchantOrderReq) (*OrderCommandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShipMerchantOrder not implemented")
}
func (UnimplementedOrderServer) ConfirmReceipt(context.Context, *ConfirmReceiptReq) (*OrderCommandResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmReceipt not implemented")
}
func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}
func (UnimplementedOrderServer) testEmbeddedByValue()               {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc.ServiceRegistrar, srv OrderServer) {
	// If the following call pancis, it indicates UnimplementedOrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_PreDeduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreDeductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).PreDeduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_PreDeduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).PreDeduct(ctx, req.(*PreDeductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_PreDeductRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreDeductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).PreDeductRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_PreDeductRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).PreDeductRollback(ctx, req.(*PreDeductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrderRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrderRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CreateOrderRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrderRollback(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_MarkOrderPaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkOrderPaidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).MarkOrderPaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_MarkOrderPaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).MarkOrderPaid(ctx, req.(*MarkOrderPaidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_GetOrderDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrderDetail(ctx, req.(*GetOrderDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_RequestRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).RequestRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_RequestRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).RequestRefund(ctx, req.(*RequestRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_AuditRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).AuditRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_AuditRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).AuditRefund(ctx, req.(*AuditRefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CancelUserOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelUserOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CancelUserOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CancelUserOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CancelUserOrder(ctx, req.(*CancelUserOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CloseAdminOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAdminOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CloseAdminOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_CloseAdminOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CloseAdminOrder(ctx, req.(*CloseAdminOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ShipAdminOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipAdminOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ShipAdminOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ShipAdminOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ShipAdminOrder(ctx, req.(*ShipAdminOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ShipMerchantOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipMerchantOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ShipMerchantOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ShipMerchantOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ShipMerchantOrder(ctx, req.(*ShipMerchantOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_ConfirmReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmReceiptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).ConfirmReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Order_ConfirmReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).ConfirmReceipt(ctx, req.(*ConfirmReceiptReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc.ServiceDesc for Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreDeduct",
			Handler:    _Order_PreDeduct_Handler,
		},
		{
			MethodName: "PreDeductRollback",
			Handler:    _Order_PreDeductRollback_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "CreateOrderRollback",
			Handler:    _Order_CreateOrderRollback_Handler,
		},
		{
			MethodName: "MarkOrderPaid",
			Handler:    _Order_MarkOrderPaid_Handler,
		},
		{
			MethodName: "GetOrderDetail",
			Handler:    _Order_GetOrderDetail_Handler,
		},
		{
			MethodName: "RequestRefund",
			Handler:    _Order_RequestRefund_Handler,
		},
		{
			MethodName: "AuditRefund",
			Handler:    _Order_AuditRefund_Handler,
		},
		{
			MethodName: "CancelUserOrder",
			Handler:    _Order_CancelUserOrder_Handler,
		},
		{
			MethodName: "CloseAdminOrder",
			Handler:    _Order_CloseAdminOrder_Handler,
		},
		{
			MethodName: "ShipAdminOrder",
			Handler:    _Order_ShipAdminOrder_Handler,
		},
		{
			MethodName: "ShipMerchantOrder",
			Handler:    _Order_ShipMerchantOrder_Handler,
		},
		{
			MethodName: "ConfirmReceipt",
			Handler:    _Order_ConfirmReceipt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/order/rpc/order.proto",
}
