// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreDeductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreDeductReq) Reset() {
	*x = PreDeductReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreDeductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreDeductReq) ProtoMessage() {}

func (x *PreDeductReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreDeductReq.ProtoReflect.Descriptor instead.
func (*PreDeductReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *PreDeductReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *PreDeductReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PreDeductReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CreateOrderReq struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	OrderId   string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId    int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount    int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 幂等请求id
	RequestId        string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpectedPriceFen int64  `protobuf:"varint,6,opt,name=expected_price_fen,json=expectedPriceFen,proto3" json:"expected_price_fen,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateOrderReq) GetExpectedPriceFen() int64 {
	if x != nil {
		return x.ExpectedPriceFen
	}
	return 0
}

type CreateOrderResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PayableAmountFen int64                  `protobuf:"varint,3,opt,name=payable_amount_fen,json=payableAmountFen,proto3" json:"payable_amount_fen,omitempty"`
	PaymentOrderId   string                 `protobuf:"bytes,4,opt,name=payment_order_id,json=paymentOrderId,proto3" json:"payment_order_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderResp) GetPayableAmountFen() int64 {
	if x != nil {
		return x.PayableAmountFen
	}
	return 0
}

func (x *CreateOrderResp) GetPaymentOrderId() string {
	if x != nil {
		return x.PaymentOrderId
	}
	return ""
}

type MarkOrderPaidReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentOrderId string                 `protobuf:"bytes,2,opt,name=payment_order_id,json=paymentOrderId,proto3" json:"payment_order_id,omitempty"`
	OutTradeNo     string                 `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	CallbackBody   string                 `protobuf:"bytes,4,opt,name=callback_body,json=callbackBody,proto3" json:"callback_body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkOrderPaidReq) Reset() {
	*x = MarkOrderPaidReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderPaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderPaidReq) ProtoMessage() {}

func (x *MarkOrderPaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderPaidReq.ProtoReflect.Descriptor instead.
func (*MarkOrderPaidReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *MarkOrderPaidReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarkOrderPaidReq) GetPaymentOrderId() string {
	if x != nil {
		return x.PaymentOrderId
	}
	return ""
}

func (x *MarkOrderPaidReq) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *MarkOrderPaidReq) GetCallbackBody() string {
	if x != nil {
		return x.CallbackBody
	}
	return ""
}

type MarkOrderPaidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOrderPaidResp) Reset() {
	*x = MarkOrderPaidResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderPaidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderPaidResp) ProtoMessage() {}

func (x *MarkOrderPaidResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderPaidResp.ProtoReflect.Descriptor instead.
func (*MarkOrderPaidResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *MarkOrderPaidResp) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *MarkOrderPaidResp) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

type CreatePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePaymentReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreatePaymentResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentOrderId   string                 `protobuf:"bytes,2,opt,name=payment_order_id,json=paymentOrderId,proto3" json:"payment_order_id,omitempty"`
	OutTradeNo       string                 `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	PayableAmountFen int64                  `protobuf:"varint,4,opt,name=payable_amount_fen,json=payableAmountFen,proto3" json:"payable_amount_fen,omitempty"`
	PaymentStatus    string                 `protobuf:"bytes,5,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	Provider         string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	QrUrl            string                 `protobuf:"bytes,7,opt,name=qr_url,json=qrUrl,proto3" json:"qr_url,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePaymentResp) Reset() {
	*x = CreatePaymentResp{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResp) ProtoMessage() {}

func (x *CreatePaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResp.ProtoReflect.Descriptor instead.
func (*CreatePaymentResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePaymentResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentResp) GetPaymentOrderId() string {
	if x != nil {
		return x.PaymentOrderId
	}
	return ""
}

func (x *CreatePaymentResp) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *CreatePaymentResp) GetPayableAmountFen() int64 {
	if x != nil {
		return x.PayableAmountFen
	}
	return 0
}

func (x *CreatePaymentResp) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *CreatePaymentResp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreatePaymentResp) GetQrUrl() string {
	if x != nil {
		return x.QrUrl
	}
	return ""
}

func (x *CreatePaymentResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type HandlePaymentNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	RawBody       string                 `protobuf:"bytes,2,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentNotificationReq) Reset() {
	*x = HandlePaymentNotificationReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentNotificationReq) ProtoMessage() {}

func (x *HandlePaymentNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentNotificationReq.ProtoReflect.Descriptor instead.
func (*HandlePaymentNotificationReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *HandlePaymentNotificationReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *HandlePaymentNotificationReq) GetRawBody() string {
	if x != nil {
		return x.RawBody
	}
	return ""
}

type HandlePaymentNotificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentNotificationResp) Reset() {
	*x = HandlePaymentNotificationResp{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentNotificationResp) ProtoMessage() {}

func (x *HandlePaymentNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentNotificationResp.ProtoReflect.Descriptor instead.
func (*HandlePaymentNotificationResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *HandlePaymentNotificationResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandlePaymentNotificationResp) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

type GetOrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailReq) Reset() {
	*x = GetOrderDetailReq{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailReq) ProtoMessage() {}

func (x *GetOrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailReq.ProtoReflect.Descriptor instead.
func (*GetOrderDetailReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderDetailReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderDetailResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderStatus       string                 `protobuf:"bytes,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PayableAmountFen  int64                  `protobuf:"varint,4,opt,name=payable_amount_fen,json=payableAmountFen,proto3" json:"payable_amount_fen,omitempty"`
	PaymentStatus     string                 `protobuf:"bytes,5,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	OriginPriceFen    int64                  `protobuf:"varint,6,opt,name=origin_price_fen,json=originPriceFen,proto3" json:"origin_price_fen,omitempty"`
	DiscountAmountFen int64                  `protobuf:"varint,7,opt,name=discount_amount_fen,json=discountAmountFen,proto3" json:"discount_amount_fen,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderDetailResp) Reset() {
	*x = GetOrderDetailResp{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResp) ProtoMessage() {}

func (x *GetOrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResp.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderDetailResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderDetailResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderDetailResp) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *GetOrderDetailResp) GetPayableAmountFen() int64 {
	if x != nil {
		return x.PayableAmountFen
	}
	return 0
}

func (x *GetOrderDetailResp) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *GetOrderDetailResp) GetOriginPriceFen() int64 {
	if x != nil {
		return x.OriginPriceFen
	}
	return 0
}

func (x *GetOrderDetailResp) GetDiscountAmountFen() int64 {
	if x != nil {
		return x.DiscountAmountFen
	}
	return 0
}

type RequestRefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RequesterRole string                 `protobuf:"bytes,3,opt,name=requester_role,json=requesterRole,proto3" json:"requester_role,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRefundReq) Reset() {
	*x = RequestRefundReq{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRefundReq) ProtoMessage() {}

func (x *RequestRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRefundReq.ProtoReflect.Descriptor instead.
func (*RequestRefundReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *RequestRefundReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RequestRefundReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *RequestRefundReq) GetRequesterRole() string {
	if x != nil {
		return x.RequesterRole
	}
	return ""
}

func (x *RequestRefundReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RequestRefundReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RequestRefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	RefundStatus  int64                  `protobuf:"varint,4,opt,name=refund_status,json=refundStatus,proto3" json:"refund_status,omitempty"`
	Repeated      bool                   `protobuf:"varint,5,opt,name=repeated,proto3" json:"repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRefundResp) Reset() {
	*x = RequestRefundResp{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRefundResp) ProtoMessage() {}

func (x *RequestRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRefundResp.ProtoReflect.Descriptor instead.
func (*RequestRefundResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *RequestRefundResp) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *RequestRefundResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RequestRefundResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *RequestRefundResp) GetRefundStatus() int64 {
	if x != nil {
		return x.RefundStatus
	}
	return 0
}

func (x *RequestRefundResp) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

type AuditRefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRefundReq) Reset() {
	*x = AuditRefundReq{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRefundReq) ProtoMessage() {}

func (x *AuditRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRefundReq.ProtoReflect.Descriptor instead.
func (*AuditRefundReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *AuditRefundReq) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *AuditRefundReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *AuditRefundReq) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *AuditRefundReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AuditRefundReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AuditRefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	RefundStatus  int64                  `protobuf:"varint,4,opt,name=refund_status,json=refundStatus,proto3" json:"refund_status,omitempty"`
	Repeated      bool                   `protobuf:"varint,5,opt,name=repeated,proto3" json:"repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRefundResp) Reset() {
	*x = AuditRefundResp{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRefundResp) ProtoMessage() {}

func (x *AuditRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRefundResp.ProtoReflect.Descriptor instead.
func (*AuditRefundResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *AuditRefundResp) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *AuditRefundResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AuditRefundResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *AuditRefundResp) GetRefundStatus() int64 {
	if x != nil {
		return x.RefundStatus
	}
	return 0
}

func (x *AuditRefundResp) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

type OrderCommandMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCommandMeta) Reset() {
	*x = OrderCommandMeta{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCommandMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommandMeta) ProtoMessage() {}

func (x *OrderCommandMeta) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommandMeta.ProtoReflect.Descriptor instead.
func (*OrderCommandMeta) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *OrderCommandMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OrderCommandMeta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OrderCommandMeta) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderCommandMeta) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *OrderCommandMeta) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CancelUserOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Meta          *OrderCommandMeta      `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUserOrderReq) Reset() {
	*x = CancelUserOrderReq{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUserOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUserOrderReq) ProtoMessage() {}

func (x *CancelUserOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUserOrderReq.ProtoReflect.Descriptor instead.
func (*CancelUserOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *CancelUserOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelUserOrderReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelUserOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelUserOrderReq) GetMeta() *OrderCommandMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CloseAdminOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Meta          *OrderCommandMeta      `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAdminOrderReq) Reset() {
	*x = CloseAdminOrderReq{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAdminOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAdminOrderReq) ProtoMessage() {}

func (x *CloseAdminOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAdminOrderReq.ProtoReflect.Descriptor instead.
func (*CloseAdminOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *CloseAdminOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CloseAdminOrderReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CloseAdminOrderReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *CloseAdminOrderReq) GetMeta() *OrderCommandMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ShipAdminOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Meta          *OrderCommandMeta      `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipAdminOrderReq) Reset() {
	*x = ShipAdminOrderReq{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipAdminOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipAdminOrderReq) ProtoMessage() {}

func (x *ShipAdminOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipAdminOrderReq.ProtoReflect.Descriptor instead.
func (*ShipAdminOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

func (x *ShipAdminOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipAdminOrderReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *ShipAdminOrderReq) GetMeta() *OrderCommandMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ShipMerchantOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Meta          *OrderCommandMeta      `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipMerchantOrderReq) Reset() {
	*x = ShipMerchantOrderReq{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipMerchantOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipMerchantOrderReq) ProtoMessage() {}

func (x *ShipMerchantOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipMerchantOrderReq.ProtoReflect.Descriptor instead.
func (*ShipMerchantOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{19}
}

func (x *ShipMerchantOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipMerchantOrderReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *ShipMerchantOrderReq) GetMeta() *OrderCommandMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ConfirmReceiptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Meta          *OrderCommandMeta      `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReceiptReq) Reset() {
	*x = ConfirmReceiptReq{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReceiptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReceiptReq) ProtoMessage() {}

func (x *ConfirmReceiptReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReceiptReq.ProtoReflect.Descriptor instead.
func (*ConfirmReceiptReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{20}
}

func (x *ConfirmReceiptReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmReceiptReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmReceiptReq) GetMeta() *OrderCommandMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type OrderCommandResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	Repeated      bool                   `protobuf:"varint,3,opt,name=repeated,proto3" json:"repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCommandResp) Reset() {
	*x = OrderCommandResp{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCommandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommandResp) ProtoMessage() {}

func (x *OrderCommandResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommandResp.ProtoReflect.Descriptor instead.
func (*OrderCommandResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{21}
}

func (x *OrderCommandResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCommandResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *OrderCommandResp) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{22}
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"`\n" +
	"\fPreDeductReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"\xc8\x01\n" +
	"\x0eCreateOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12,\n" +
	"\x12expected_price_fen\x18\x06 \x01(\x03R\x10expectedPriceFen\"\x9c\x01\n" +
	"\x0fCreateOrderResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x12payable_amount_fen\x18\x03 \x01(\x03R\x10payableAmountFen\x12(\n" +
	"\x10payment_order_id\x18\x04 \x01(\tR\x0epaymentOrderId\"\x9e\x01\n" +
	"\x10MarkOrderPaidReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x10payment_order_id\x18\x02 \x01(\tR\x0epaymentOrderId\x12 \n" +
	"\fout_trade_no\x18\x03 \x01(\tR\n" +
	"outTradeNo\x12#\n" +
	"\rcallback_body\x18\x04 \x01(\tR\fcallbackBody\"P\n" +
	"\x11MarkOrderPaidResp\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\x12!\n" +
	"\forder_status\x18\x02 \x01(\tR\vorderStatus\"F\n" +
	"\x10CreatePaymentReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xa1\x02\n" +
	"\x11CreatePaymentResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x10payment_order_id\x18\x02 \x01(\tR\x0epaymentOrderId\x12 \n" +
	"\fout_trade_no\x18\x03 \x01(\tR\n" +
	"outTradeNo\x12,\n" +
	"\x12payable_amount_fen\x18\x04 \x01(\x03R\x10payableAmountFen\x12%\n" +
	"\x0epayment_status\x18\x05 \x01(\tR\rpaymentStatus\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12\x15\n" +
	"\x06qr_url\x18\a \x01(\tR\x05qrUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\"U\n" +
	"\x1cHandlePaymentNotificationReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\braw_body\x18\x02 \x01(\tR\arawBody\"^\n" +
	"\x1dHandlePaymentNotificationResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12!\n" +
	"\forder_status\x18\x02 \x01(\tR\vorderStatus\".\n" +
	"\x11GetOrderDetailReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x9a\x02\n" +
	"\x12GetOrderDetailResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\forder_status\x18\x03 \x01(\tR\vorderStatus\x12,\n" +
	"\x12payable_amount_fen\x18\x04 \x01(\x03R\x10payableAmountFen\x12%\n" +
	"\x0epayment_status\x18\x05 \x01(\tR\rpaymentStatus\x12(\n" +
	"\x10origin_price_fen\x18\x06 \x01(\x03R\x0eoriginPriceFen\x12.\n" +
	"\x13discount_amount_fen\x18\a \x01(\x03R\x11discountAmountFen\"\xae\x01\n" +
	"\x10RequestRefundReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\x12%\n" +
	"\x0erequester_role\x18\x03 \x01(\tR\rrequesterRole\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xaf\x01\n" +
	"\x11RequestRefundResp\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x03 \x01(\x03R\vorderStatus\x12#\n" +
	"\rrefund_status\x18\x04 \x01(\x03R\frefundStatus\x12\x1a\n" +
	"\brepeated\x18\x05 \x01(\bR\brepeated\"\x9f\x01\n" +
	"\x0eAuditRefundReq\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xad\x01\n" +
	"\x0fAuditRefundResp\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x03 \x01(\x03R\vorderStatus\x12#\n" +
	"\rrefund_status\x18\x04 \x01(\x03R\frefundStatus\x12\x1a\n" +
	"\brepeated\x18\x05 \x01(\bR\brepeated\"\x9a\x01\n" +
	"\x10OrderCommandMeta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\x03R\n" +
	"merchantId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x8d\x01\n" +
	"\x12CancelUserOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12+\n" +
	"\x04meta\x18\x04 \x01(\v2\x17.order.OrderCommandMetaR\x04meta\"\x95\x01\n" +
	"\x12CloseAdminOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId\x12+\n" +
	"\x04meta\x18\x04 \x01(\v2\x17.order.OrderCommandMetaR\x04meta\"|\n" +
	"\x11ShipAdminOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12+\n" +
	"\x04meta\x18\x03 \x01(\v2\x17.order.OrderCommandMetaR\x04meta\"\x7f\n" +
	"\x14ShipMerchantOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\x12+\n" +
	"\x04meta\x18\x03 \x01(\v2\x17.order.OrderCommandMetaR\x04meta\"t\n" +
	"\x11ConfirmReceiptReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12+\n" +
	"\x04meta\x18\x03 \x01(\v2\x17.order.OrderCommandMetaR\x04meta\"l\n" +
	"\x10OrderCommandResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x02 \x01(\x03R\vorderStatus\x12\x1a\n" +
	"\brepeated\x18\x03 \x01(\bR\brepeated\"\a\n" +
	"\x05Empty2\x85\b\n" +
	"\x05Order\x12.\n" +
	"\tPreDeduct\x12\x13.order.PreDeductReq\x1a\f.order.Empty\x126\n" +
	"\x11PreDeductRollback\x12\x13.order.PreDeductReq\x1a\f.order.Empty\x12<\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x12:\n" +
	"\x13CreateOrderRollback\x12\x15.order.CreateOrderReq\x1a\f.order.Empty\x12B\n" +
	"\rCreatePayment\x12\x17.order.CreatePaymentReq\x1a\x18.order.CreatePaymentResp\x12f\n" +
	"\x19HandlePaymentNotification\x12#.order.HandlePaymentNotificationReq\x1a$.order.HandlePaymentNotificationResp\x12B\n" +
	"\rMarkOrderPaid\x12\x17.order.MarkOrderPaidReq\x1a\x18.order.MarkOrderPaidResp\x12E\n" +
	"\x0eGetOrderDetail\x12\x18.order.GetOrderDetailReq\x1a\x19.order.GetOrderDetailResp\x12B\n" +
	"\rRequestRefund\x12\x17.order.RequestRefundReq\x1a\x18.order.RequestRefundResp\x12<\n" +
	"\vAuditRefund\x12\x15.order.AuditRefundReq\x1a\x16.order.AuditRefundResp\x12E\n" +
	"\x0fCancelUserOrder\x12\x19.order.CancelUserOrderReq\x1a\x17.order.OrderCommandResp\x12E\n" +
	"\x0fCloseAdminOrder\x12\x19.order.CloseAdminOrderReq\x1a\x17.order.OrderCommandResp\x12C\n" +
	"\x0eShipAdminOrder\x12\x18.order.ShipAdminOrderReq\x1a\x17.order.OrderCommandResp\x12I\n" +
	"\x11ShipMerchantOrder\x12\x1b.order.ShipMerchantOrderReq\x1a\x17.order.OrderCommandResp\x12C\n" +
	"\x0eConfirmReceipt\x12\x18.order.ConfirmReceiptReq\x1a\x17.order.OrderCommandRespB&Z$flash-mall/app/order/rpc/order;orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_order_proto_goTypes = []any{
	(*PreDeductReq)(nil),                  // 0: order.PreDeductReq
	(*CreateOrderReq)(nil),                // 1: order.CreateOrderReq
	(*CreateOrderResp)(nil),               // 2: order.CreateOrderResp
	(*MarkOrderPaidReq)(nil),              // 3: order.MarkOrderPaidReq
	(*MarkOrderPaidResp)(nil),             // 4: order.MarkOrderPaidResp
	(*CreatePaymentReq)(nil),              // 5: order.CreatePaymentReq
	(*CreatePaymentResp)(nil),             // 6: order.CreatePaymentResp
	(*HandlePaymentNotificationReq)(nil),  // 7: order.HandlePaymentNotificationReq
	(*HandlePaymentNotificationResp)(nil), // 8: order.HandlePaymentNotificationResp
	(*GetOrderDetailReq)(nil),             // 9: order.GetOrderDetailReq
	(*GetOrderDetailResp)(nil),            // 10: order.GetOrderDetailResp
	(*RequestRefundReq)(nil),              // 11: order.RequestRefundReq
	(*RequestRefundResp)(nil),             // 12: order.RequestRefundResp
	(*AuditRefundReq)(nil),                // 13: order.AuditRefundReq
	(*AuditRefundResp)(nil),               // 14: order.AuditRefundResp
	(*OrderCommandMeta)(nil),              // 15: order.OrderCommandMeta
	(*CancelUserOrderReq)(nil),            // 16: order.CancelUserOrderReq
	(*CloseAdminOrderReq)(nil),            // 17: order.CloseAdminOrderReq
	(*ShipAdminOrderReq)(nil),             // 18: order.ShipAdminOrderReq
	(*ShipMerchantOrderReq)(nil),          // 19: order.ShipMerchantOrderReq
	(*ConfirmReceiptReq)(nil),             // 20: order.ConfirmReceiptReq
	(*OrderCommandResp)(nil),              // 21: order.OrderCommandResp
	(*Empty)(nil),                         // 22: order.Empty
}
var file_order_proto_depIdxs = []int32{
	15, // 0: order.CancelUserOrderReq.meta:type_name -> order.OrderCommandMeta
	15, // 1: order.CloseAdminOrderReq.meta:type_name -> order.OrderCommandMeta
	15, // 2: order.ShipAdminOrderReq.meta:type_name -> order.OrderCommandMeta
	15, // 3: order.ShipMerchantOrderReq.meta:type_name -> order.OrderCommandMeta
	15, // 4: order.ConfirmReceiptReq.meta:type_name -> order.OrderCommandMeta
	0,  // 5: order.Order.PreDeduct:input_type -> order.PreDeductReq
	0,  // 6: order.Order.PreDeductRollback:input_type -> order.PreDeductReq
	1,  // 7: order.Order.CreateOrder:input_type -> order.CreateOrderReq
	1,  // 8: order.Order.CreateOrderRollback:input_type -> order.CreateOrderReq
	5,  // 9: order.Order.CreatePayment:input_type -> order.CreatePaymentReq
	7,  // 10: order.Order.HandlePaymentNotification:input_type -> order.HandlePaymentNotificationReq
	3,  // 11: order.Order.MarkOrderPaid:input_type -> order.MarkOrderPaidReq
	9,  // 12: order.Order.GetOrderDetail:input_type -> order.GetOrderDetailReq
	11, // 13: order.Order.RequestRefund:input_type -> order.RequestRefundReq
	13, // 14: order.Order.AuditRefund:input_type -> order.AuditRefundReq
	16, // 15: order.Order.CancelUserOrder:input_type -> order.CancelUserOrderReq
	17, // 16: order.Order.CloseAdminOrder:input_type -> order.CloseAdminOrderReq
	18, // 17: order.Order.ShipAdminOrder:input_type -> order.ShipAdminOrderReq
	19, // 18: order.Order.ShipMerchantOrder:input_type -> order.ShipMerchantOrderReq
	20, // 19: order.Order.ConfirmReceipt:input_type -> order.ConfirmReceiptReq
	22, // 20: order.Order.PreDeduct:output_type -> order.Empty
	22, // 21: order.Order.PreDeductRollback:output_type -> order.Empty
	2,  // 22: order.Order.CreateOrder:output_type -> order.CreateOrderResp
	22, // 23: order.Order.CreateOrderRollback:output_type -> order.Empty
	6,  // 24: order.Order.CreatePayment:output_type -> order.CreatePaymentResp
	8,  // 25: order.Order.HandlePaymentNotification:output_type -> order.HandlePaymentNotificationResp
	4,  // 26: order.Order.MarkOrderPaid:output_type -> order.MarkOrderPaidResp
	10, // 27: order.Order.GetOrderDetail:output_type -> order.GetOrderDetailResp
	12, // 28: order.Order.RequestRefund:output_type -> order.RequestRefundResp
	14, // 29: order.Order.AuditRefund:output_type -> order.AuditRefundResp
	21, // 30: order.Order.CancelUserOrder:output_type -> order.OrderCommandResp
	21, // 31: order.Order.CloseAdminOrder:output_type -> order.OrderCommandResp
	21, // 32: order.Order.ShipAdminOrder:output_type -> order.OrderCommandResp
	21, // 33: order.Order.ShipMerchantOrder:output_type -> order.OrderCommandResp
	21, // 34: order.Order.ConfirmReceipt:output_type -> order.OrderCommandResp
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
