// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: app/order/rpc/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreDeductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreDeductReq) Reset() {
	*x = PreDeductReq{}
	mi := &file_app_order_rpc_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreDeductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreDeductReq) ProtoMessage() {}

func (x *PreDeductReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreDeductReq.ProtoReflect.Descriptor instead.
func (*PreDeductReq) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{0}
}

func (x *PreDeductReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *PreDeductReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PreDeductReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CreateOrderReq struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	OrderId   string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId    int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount    int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 幂等请求id
	RequestId        string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpectedPriceFen int64  `protobuf:"varint,6,opt,name=expected_price_fen,json=expectedPriceFen,proto3" json:"expected_price_fen,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_app_order_rpc_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateOrderReq) GetExpectedPriceFen() int64 {
	if x != nil {
		return x.ExpectedPriceFen
	}
	return 0
}

type CreateOrderResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PayableAmountFen int64                  `protobuf:"varint,3,opt,name=payable_amount_fen,json=payableAmountFen,proto3" json:"payable_amount_fen,omitempty"`
	PaymentOrderId   string                 `protobuf:"bytes,4,opt,name=payment_order_id,json=paymentOrderId,proto3" json:"payment_order_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_app_order_rpc_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderResp) GetPayableAmountFen() int64 {
	if x != nil {
		return x.PayableAmountFen
	}
	return 0
}

func (x *CreateOrderResp) GetPaymentOrderId() string {
	if x != nil {
		return x.PaymentOrderId
	}
	return ""
}

type MarkOrderPaidReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentOrderId string                 `protobuf:"bytes,2,opt,name=payment_order_id,json=paymentOrderId,proto3" json:"payment_order_id,omitempty"`
	OutTradeNo     string                 `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	CallbackBody   string                 `protobuf:"bytes,4,opt,name=callback_body,json=callbackBody,proto3" json:"callback_body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkOrderPaidReq) Reset() {
	*x = MarkOrderPaidReq{}
	mi := &file_app_order_rpc_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderPaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderPaidReq) ProtoMessage() {}

func (x *MarkOrderPaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderPaidReq.ProtoReflect.Descriptor instead.
func (*MarkOrderPaidReq) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{3}
}

func (x *MarkOrderPaidReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *MarkOrderPaidReq) GetPaymentOrderId() string {
	if x != nil {
		return x.PaymentOrderId
	}
	return ""
}

func (x *MarkOrderPaidReq) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *MarkOrderPaidReq) GetCallbackBody() string {
	if x != nil {
		return x.CallbackBody
	}
	return ""
}

type MarkOrderPaidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOrderPaidResp) Reset() {
	*x = MarkOrderPaidResp{}
	mi := &file_app_order_rpc_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderPaidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderPaidResp) ProtoMessage() {}

func (x *MarkOrderPaidResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderPaidResp.ProtoReflect.Descriptor instead.
func (*MarkOrderPaidResp) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{4}
}

func (x *MarkOrderPaidResp) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *MarkOrderPaidResp) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

type GetOrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailReq) Reset() {
	*x = GetOrderDetailReq{}
	mi := &file_app_order_rpc_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailReq) ProtoMessage() {}

func (x *GetOrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailReq.ProtoReflect.Descriptor instead.
func (*GetOrderDetailReq) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderDetailReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderDetailResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderStatus       string                 `protobuf:"bytes,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PayableAmountFen  int64                  `protobuf:"varint,4,opt,name=payable_amount_fen,json=payableAmountFen,proto3" json:"payable_amount_fen,omitempty"`
	PaymentStatus     string                 `protobuf:"bytes,5,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	OriginPriceFen    int64                  `protobuf:"varint,6,opt,name=origin_price_fen,json=originPriceFen,proto3" json:"origin_price_fen,omitempty"`
	DiscountAmountFen int64                  `protobuf:"varint,7,opt,name=discount_amount_fen,json=discountAmountFen,proto3" json:"discount_amount_fen,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOrderDetailResp) Reset() {
	*x = GetOrderDetailResp{}
	mi := &file_app_order_rpc_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResp) ProtoMessage() {}

func (x *GetOrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResp.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResp) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderDetailResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderDetailResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderDetailResp) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *GetOrderDetailResp) GetPayableAmountFen() int64 {
	if x != nil {
		return x.PayableAmountFen
	}
	return 0
}

func (x *GetOrderDetailResp) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *GetOrderDetailResp) GetOriginPriceFen() int64 {
	if x != nil {
		return x.OriginPriceFen
	}
	return 0
}

func (x *GetOrderDetailResp) GetDiscountAmountFen() int64 {
	if x != nil {
		return x.DiscountAmountFen
	}
	return 0
}

type RequestRefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RequesterRole string                 `protobuf:"bytes,3,opt,name=requester_role,json=requesterRole,proto3" json:"requester_role,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRefundReq) Reset() {
	*x = RequestRefundReq{}
	mi := &file_app_order_rpc_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRefundReq) ProtoMessage() {}

func (x *RequestRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRefundReq.ProtoReflect.Descriptor instead.
func (*RequestRefundReq) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{7}
}

func (x *RequestRefundReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RequestRefundReq) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *RequestRefundReq) GetRequesterRole() string {
	if x != nil {
		return x.RequesterRole
	}
	return ""
}

func (x *RequestRefundReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RequestRefundReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RequestRefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	RefundStatus  int64                  `protobuf:"varint,4,opt,name=refund_status,json=refundStatus,proto3" json:"refund_status,omitempty"`
	Repeated      bool                   `protobuf:"varint,5,opt,name=repeated,proto3" json:"repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRefundResp) Reset() {
	*x = RequestRefundResp{}
	mi := &file_app_order_rpc_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRefundResp) ProtoMessage() {}

func (x *RequestRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRefundResp.ProtoReflect.Descriptor instead.
func (*RequestRefundResp) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{8}
}

func (x *RequestRefundResp) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *RequestRefundResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RequestRefundResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *RequestRefundResp) GetRefundStatus() int64 {
	if x != nil {
		return x.RefundStatus
	}
	return 0
}

func (x *RequestRefundResp) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

type AuditRefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRefundReq) Reset() {
	*x = AuditRefundReq{}
	mi := &file_app_order_rpc_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRefundReq) ProtoMessage() {}

func (x *AuditRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRefundReq.ProtoReflect.Descriptor instead.
func (*AuditRefundReq) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{9}
}

func (x *AuditRefundReq) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *AuditRefundReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *AuditRefundReq) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *AuditRefundReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AuditRefundReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AuditRefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	RefundStatus  int64                  `protobuf:"varint,4,opt,name=refund_status,json=refundStatus,proto3" json:"refund_status,omitempty"`
	Repeated      bool                   `protobuf:"varint,5,opt,name=repeated,proto3" json:"repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRefundResp) Reset() {
	*x = AuditRefundResp{}
	mi := &file_app_order_rpc_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRefundResp) ProtoMessage() {}

func (x *AuditRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRefundResp.ProtoReflect.Descriptor instead.
func (*AuditRefundResp) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{10}
}

func (x *AuditRefundResp) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *AuditRefundResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AuditRefundResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *AuditRefundResp) GetRefundStatus() int64 {
	if x != nil {
		return x.RefundStatus
	}
	return 0
}

func (x *AuditRefundResp) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_app_order_rpc_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_rpc_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_order_rpc_order_proto_rawDescGZIP(), []int{11}
}

var File_app_order_rpc_order_proto protoreflect.FileDescriptor

const file_app_order_rpc_order_proto_rawDesc = "" +
	"\n" +
	"\x19app/order/rpc/order.proto\x12\x05order\"`\n" +
	"\fPreDeductReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"\xc8\x01\n" +
	"\x0eCreateOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12,\n" +
	"\x12expected_price_fen\x18\x06 \x01(\x03R\x10expectedPriceFen\"\x9c\x01\n" +
	"\x0fCreateOrderResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x12payable_amount_fen\x18\x03 \x01(\x03R\x10payableAmountFen\x12(\n" +
	"\x10payment_order_id\x18\x04 \x01(\tR\x0epaymentOrderId\"\x9e\x01\n" +
	"\x10MarkOrderPaidReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x10payment_order_id\x18\x02 \x01(\tR\x0epaymentOrderId\x12 \n" +
	"\fout_trade_no\x18\x03 \x01(\tR\n" +
	"outTradeNo\x12#\n" +
	"\rcallback_body\x18\x04 \x01(\tR\fcallbackBody\"P\n" +
	"\x11MarkOrderPaidResp\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\x12!\n" +
	"\forder_status\x18\x02 \x01(\tR\vorderStatus\".\n" +
	"\x11GetOrderDetailReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x9a\x02\n" +
	"\x12GetOrderDetailResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\forder_status\x18\x03 \x01(\tR\vorderStatus\x12,\n" +
	"\x12payable_amount_fen\x18\x04 \x01(\x03R\x10payableAmountFen\x12%\n" +
	"\x0epayment_status\x18\x05 \x01(\tR\rpaymentStatus\x12(\n" +
	"\x10origin_price_fen\x18\x06 \x01(\x03R\x0eoriginPriceFen\x12.\n" +
	"\x13discount_amount_fen\x18\a \x01(\x03R\x11discountAmountFen\"\xae\x01\n" +
	"\x10RequestRefundReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\x12%\n" +
	"\x0erequester_role\x18\x03 \x01(\tR\rrequesterRole\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xaf\x01\n" +
	"\x11RequestRefundResp\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x03 \x01(\x03R\vorderStatus\x12#\n" +
	"\rrefund_status\x18\x04 \x01(\x03R\frefundStatus\x12\x1a\n" +
	"\brepeated\x18\x05 \x01(\bR\brepeated\"\x9f\x01\n" +
	"\x0eAuditRefundReq\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xad\x01\n" +
	"\x0fAuditRefundResp\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\forder_status\x18\x03 \x01(\x03R\vorderStatus\x12#\n" +
	"\rrefund_status\x18\x04 \x01(\x03R\frefundStatus\x12\x1a\n" +
	"\brepeated\x18\x05 \x01(\bR\brepeated\"\a\n" +
	"\x05Empty2\xf6\x03\n" +
	"\x05Order\x12.\n" +
	"\tPreDeduct\x12\x13.order.PreDeductReq\x1a\f.order.Empty\x126\n" +
	"\x11PreDeductRollback\x12\x13.order.PreDeductReq\x1a\f.order.Empty\x12<\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x12:\n" +
	"\x13CreateOrderRollback\x12\x15.order.CreateOrderReq\x1a\f.order.Empty\x12B\n" +
	"\rMarkOrderPaid\x12\x17.order.MarkOrderPaidReq\x1a\x18.order.MarkOrderPaidResp\x12E\n" +
	"\x0eGetOrderDetail\x12\x18.order.GetOrderDetailReq\x1a\x19.order.GetOrderDetailResp\x12B\n" +
	"\rRequestRefund\x12\x17.order.RequestRefundReq\x1a\x18.order.RequestRefundResp\x12<\n" +
	"\vAuditRefund\x12\x15.order.AuditRefundReq\x1a\x16.order.AuditRefundRespB&Z$flash-mall/app/order/rpc/order;orderb\x06proto3"

var (
	file_app_order_rpc_order_proto_rawDescOnce sync.Once
	file_app_order_rpc_order_proto_rawDescData []byte
)

func file_app_order_rpc_order_proto_rawDescGZIP() []byte {
	file_app_order_rpc_order_proto_rawDescOnce.Do(func() {
		file_app_order_rpc_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_order_rpc_order_proto_rawDesc), len(file_app_order_rpc_order_proto_rawDesc)))
	})
	return file_app_order_rpc_order_proto_rawDescData
}

var file_app_order_rpc_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_order_rpc_order_proto_goTypes = []any{
	(*PreDeductReq)(nil),       // 0: order.PreDeductReq
	(*CreateOrderReq)(nil),     // 1: order.CreateOrderReq
	(*CreateOrderResp)(nil),    // 2: order.CreateOrderResp
	(*MarkOrderPaidReq)(nil),   // 3: order.MarkOrderPaidReq
	(*MarkOrderPaidResp)(nil),  // 4: order.MarkOrderPaidResp
	(*GetOrderDetailReq)(nil),  // 5: order.GetOrderDetailReq
	(*GetOrderDetailResp)(nil), // 6: order.GetOrderDetailResp
	(*RequestRefundReq)(nil),   // 7: order.RequestRefundReq
	(*RequestRefundResp)(nil),  // 8: order.RequestRefundResp
	(*AuditRefundReq)(nil),     // 9: order.AuditRefundReq
	(*AuditRefundResp)(nil),    // 10: order.AuditRefundResp
	(*Empty)(nil),              // 11: order.Empty
}
var file_app_order_rpc_order_proto_depIdxs = []int32{
	0,  // 0: order.Order.PreDeduct:input_type -> order.PreDeductReq
	0,  // 1: order.Order.PreDeductRollback:input_type -> order.PreDeductReq
	1,  // 2: order.Order.CreateOrder:input_type -> order.CreateOrderReq
	1,  // 3: order.Order.CreateOrderRollback:input_type -> order.CreateOrderReq
	3,  // 4: order.Order.MarkOrderPaid:input_type -> order.MarkOrderPaidReq
	5,  // 5: order.Order.GetOrderDetail:input_type -> order.GetOrderDetailReq
	7,  // 6: order.Order.RequestRefund:input_type -> order.RequestRefundReq
	9,  // 7: order.Order.AuditRefund:input_type -> order.AuditRefundReq
	11, // 8: order.Order.PreDeduct:output_type -> order.Empty
	11, // 9: order.Order.PreDeductRollback:output_type -> order.Empty
	2,  // 10: order.Order.CreateOrder:output_type -> order.CreateOrderResp
	11, // 11: order.Order.CreateOrderRollback:output_type -> order.Empty
	4,  // 12: order.Order.MarkOrderPaid:output_type -> order.MarkOrderPaidResp
	6,  // 13: order.Order.GetOrderDetail:output_type -> order.GetOrderDetailResp
	8,  // 14: order.Order.RequestRefund:output_type -> order.RequestRefundResp
	10, // 15: order.Order.AuditRefund:output_type -> order.AuditRefundResp
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_app_order_rpc_order_proto_init() }
func file_app_order_rpc_order_proto_init() {
	if File_app_order_rpc_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_order_rpc_order_proto_rawDesc), len(file_app_order_rpc_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_order_rpc_order_proto_goTypes,
		DependencyIndexes: file_app_order_rpc_order_proto_depIdxs,
		MessageInfos:      file_app_order_rpc_order_proto_msgTypes,
	}.Build()
	File_app_order_rpc_order_proto = out.File
	file_app_order_rpc_order_proto_goTypes = nil
	file_app_order_rpc_order_proto_depIdxs = nil
}
