// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package common

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ErrorCode int64

const (
	ErrorCode_OK                      ErrorCode = 0
	ErrorCode_INVALID_ARGUMENT        ErrorCode = 1001
	ErrorCode_UNAUTHORIZED            ErrorCode = 1002
	ErrorCode_FORBIDDEN               ErrorCode = 1003
	ErrorCode_NOT_FOUND               ErrorCode = 1004
	ErrorCode_CONFLICT                ErrorCode = 1005
	ErrorCode_TOO_MANY_REQUESTS       ErrorCode = 1006
	ErrorCode_INTERNAL                ErrorCode = 1007
	ErrorCode_PRODUCT_NOT_FOUND       ErrorCode = 2001
	ErrorCode_PRODUCT_OFF_SHELF       ErrorCode = 2002
	ErrorCode_STOCK_NOT_FOUND         ErrorCode = 3001
	ErrorCode_STOCK_INSUFFICIENT      ErrorCode = 3002
	ErrorCode_STOCK_RESERVE_FAILED    ErrorCode = 3003
	ErrorCode_STOCK_RECONCILE_FAILED  ErrorCode = 3004
	ErrorCode_ORDER_NOT_FOUND         ErrorCode = 4001
	ErrorCode_ORDER_STATUS_INVALID    ErrorCode = 4002
	ErrorCode_ORDER_CREATE_FAILED     ErrorCode = 4003
	ErrorCode_ORDER_ALREADY_PAID      ErrorCode = 4004
	ErrorCode_PAYMENT_STATUS_INVALID  ErrorCode = 5001
	ErrorCode_PAYMENT_FAILED          ErrorCode = 5002
	ErrorCode_REFUND_NOT_ALLOWED      ErrorCode = 6001
	ErrorCode_REFUND_NOT_FOUND        ErrorCode = 6002
	ErrorCode_REFUND_STATUS_INVALID   ErrorCode = 6003
	ErrorCode_MERCHANT_NOT_FOUND      ErrorCode = 7001
	ErrorCode_MERCHANT_NOT_BOUND      ErrorCode = 7002
	ErrorCode_MERCHANT_APPLY_PENDING  ErrorCode = 7003
	ErrorCode_MERCHANT_APPLY_REJECTED ErrorCode = 7004
)

func (p ErrorCode) String() string {
	switch p {
	case ErrorCode_OK:
		return "OK"
	case ErrorCode_INVALID_ARGUMENT:
		return "INVALID_ARGUMENT"
	case ErrorCode_UNAUTHORIZED:
		return "UNAUTHORIZED"
	case ErrorCode_FORBIDDEN:
		return "FORBIDDEN"
	case ErrorCode_NOT_FOUND:
		return "NOT_FOUND"
	case ErrorCode_CONFLICT:
		return "CONFLICT"
	case ErrorCode_TOO_MANY_REQUESTS:
		return "TOO_MANY_REQUESTS"
	case ErrorCode_INTERNAL:
		return "INTERNAL"
	case ErrorCode_PRODUCT_NOT_FOUND:
		return "PRODUCT_NOT_FOUND"
	case ErrorCode_PRODUCT_OFF_SHELF:
		return "PRODUCT_OFF_SHELF"
	case ErrorCode_STOCK_NOT_FOUND:
		return "STOCK_NOT_FOUND"
	case ErrorCode_STOCK_INSUFFICIENT:
		return "STOCK_INSUFFICIENT"
	case ErrorCode_STOCK_RESERVE_FAILED:
		return "STOCK_RESERVE_FAILED"
	case ErrorCode_STOCK_RECONCILE_FAILED:
		return "STOCK_RECONCILE_FAILED"
	case ErrorCode_ORDER_NOT_FOUND:
		return "ORDER_NOT_FOUND"
	case ErrorCode_ORDER_STATUS_INVALID:
		return "ORDER_STATUS_INVALID"
	case ErrorCode_ORDER_CREATE_FAILED:
		return "ORDER_CREATE_FAILED"
	case ErrorCode_ORDER_ALREADY_PAID:
		return "ORDER_ALREADY_PAID"
	case ErrorCode_PAYMENT_STATUS_INVALID:
		return "PAYMENT_STATUS_INVALID"
	case ErrorCode_PAYMENT_FAILED:
		return "PAYMENT_FAILED"
	case ErrorCode_REFUND_NOT_ALLOWED:
		return "REFUND_NOT_ALLOWED"
	case ErrorCode_REFUND_NOT_FOUND:
		return "REFUND_NOT_FOUND"
	case ErrorCode_REFUND_STATUS_INVALID:
		return "REFUND_STATUS_INVALID"
	case ErrorCode_MERCHANT_NOT_FOUND:
		return "MERCHANT_NOT_FOUND"
	case ErrorCode_MERCHANT_NOT_BOUND:
		return "MERCHANT_NOT_BOUND"
	case ErrorCode_MERCHANT_APPLY_PENDING:
		return "MERCHANT_APPLY_PENDING"
	case ErrorCode_MERCHANT_APPLY_REJECTED:
		return "MERCHANT_APPLY_REJECTED"
	}
	return "<UNSET>"
}

func ErrorCodeFromString(s string) (ErrorCode, error) {
	switch s {
	case "OK":
		return ErrorCode_OK, nil
	case "INVALID_ARGUMENT":
		return ErrorCode_INVALID_ARGUMENT, nil
	case "UNAUTHORIZED":
		return ErrorCode_UNAUTHORIZED, nil
	case "FORBIDDEN":
		return ErrorCode_FORBIDDEN, nil
	case "NOT_FOUND":
		return ErrorCode_NOT_FOUND, nil
	case "CONFLICT":
		return ErrorCode_CONFLICT, nil
	case "TOO_MANY_REQUESTS":
		return ErrorCode_TOO_MANY_REQUESTS, nil
	case "INTERNAL":
		return ErrorCode_INTERNAL, nil
	case "PRODUCT_NOT_FOUND":
		return ErrorCode_PRODUCT_NOT_FOUND, nil
	case "PRODUCT_OFF_SHELF":
		return ErrorCode_PRODUCT_OFF_SHELF, nil
	case "STOCK_NOT_FOUND":
		return ErrorCode_STOCK_NOT_FOUND, nil
	case "STOCK_INSUFFICIENT":
		return ErrorCode_STOCK_INSUFFICIENT, nil
	case "STOCK_RESERVE_FAILED":
		return ErrorCode_STOCK_RESERVE_FAILED, nil
	case "STOCK_RECONCILE_FAILED":
		return ErrorCode_STOCK_RECONCILE_FAILED, nil
	case "ORDER_NOT_FOUND":
		return ErrorCode_ORDER_NOT_FOUND, nil
	case "ORDER_STATUS_INVALID":
		return ErrorCode_ORDER_STATUS_INVALID, nil
	case "ORDER_CREATE_FAILED":
		return ErrorCode_ORDER_CREATE_FAILED, nil
	case "ORDER_ALREADY_PAID":
		return ErrorCode_ORDER_ALREADY_PAID, nil
	case "PAYMENT_STATUS_INVALID":
		return ErrorCode_PAYMENT_STATUS_INVALID, nil
	case "PAYMENT_FAILED":
		return ErrorCode_PAYMENT_FAILED, nil
	case "REFUND_NOT_ALLOWED":
		return ErrorCode_REFUND_NOT_ALLOWED, nil
	case "REFUND_NOT_FOUND":
		return ErrorCode_REFUND_NOT_FOUND, nil
	case "REFUND_STATUS_INVALID":
		return ErrorCode_REFUND_STATUS_INVALID, nil
	case "MERCHANT_NOT_FOUND":
		return ErrorCode_MERCHANT_NOT_FOUND, nil
	case "MERCHANT_NOT_BOUND":
		return ErrorCode_MERCHANT_NOT_BOUND, nil
	case "MERCHANT_APPLY_PENDING":
		return ErrorCode_MERCHANT_APPLY_PENDING, nil
	case "MERCHANT_APPLY_REJECTED":
		return ErrorCode_MERCHANT_APPLY_REJECTED, nil
	}
	return ErrorCode(0), fmt.Errorf("not a valid ErrorCode string")
}

func ErrorCodePtr(v ErrorCode) *ErrorCode { return &v }
func (p *ErrorCode) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ErrorCode(result.Int64)
	return
}

func (p *ErrorCode) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RequestMeta struct {
	RequestId  *string `thrift:"request_id,1,optional" frugal:"1,optional,string" json:"request_id,omitempty"`
	TraceId    *string `thrift:"trace_id,2,optional" frugal:"2,optional,string" json:"trace_id,omitempty"`
	UserId     *int64  `thrift:"user_id,3,optional" frugal:"3,optional,i64" json:"user_id,omitempty"`
	MerchantId *int64  `thrift:"merchant_id,4,optional" frugal:"4,optional,i64" json:"merchant_id,omitempty"`
	Role       *string `thrift:"role,5,optional" frugal:"5,optional,string" json:"role,omitempty"`
}

func NewRequestMeta() *RequestMeta {
	return &RequestMeta{}
}

func (p *RequestMeta) InitDefault() {
}

var RequestMeta_RequestId_DEFAULT string

func (p *RequestMeta) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return RequestMeta_RequestId_DEFAULT
	}
	return *p.RequestId
}

var RequestMeta_TraceId_DEFAULT string

func (p *RequestMeta) GetTraceId() (v string) {
	if !p.IsSetTraceId() {
		return RequestMeta_TraceId_DEFAULT
	}
	return *p.TraceId
}

var RequestMeta_UserId_DEFAULT int64

func (p *RequestMeta) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return RequestMeta_UserId_DEFAULT
	}
	return *p.UserId
}

var RequestMeta_MerchantId_DEFAULT int64

func (p *RequestMeta) GetMerchantId() (v int64) {
	if !p.IsSetMerchantId() {
		return RequestMeta_MerchantId_DEFAULT
	}
	return *p.MerchantId
}

var RequestMeta_Role_DEFAULT string

func (p *RequestMeta) GetRole() (v string) {
	if !p.IsSetRole() {
		return RequestMeta_Role_DEFAULT
	}
	return *p.Role
}
func (p *RequestMeta) SetRequestId(val *string) {
	p.RequestId = val
}
func (p *RequestMeta) SetTraceId(val *string) {
	p.TraceId = val
}
func (p *RequestMeta) SetUserId(val *int64) {
	p.UserId = val
}
func (p *RequestMeta) SetMerchantId(val *int64) {
	p.MerchantId = val
}
func (p *RequestMeta) SetRole(val *string) {
	p.Role = val
}

func (p *RequestMeta) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *RequestMeta) IsSetTraceId() bool {
	return p.TraceId != nil
}

func (p *RequestMeta) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *RequestMeta) IsSetMerchantId() bool {
	return p.MerchantId != nil
}

func (p *RequestMeta) IsSetRole() bool {
	return p.Role != nil
}

func (p *RequestMeta) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequestMeta(%+v)", *p)
}

var fieldIDToName_RequestMeta = map[int16]string{
	1: "request_id",
	2: "trace_id",
	3: "user_id",
	4: "merchant_id",
	5: "role",
}

type PageRequest struct {
	Page     int64 `thrift:"page,1,optional" frugal:"1,optional,i64" json:"page,omitempty"`
	PageSize int64 `thrift:"page_size,2,optional" frugal:"2,optional,i64" json:"page_size,omitempty"`
}

func NewPageRequest() *PageRequest {
	return &PageRequest{
		Page:     1,
		PageSize: 20,
	}
}

func (p *PageRequest) InitDefault() {
	p.Page = 1
	p.PageSize = 20
}

var PageRequest_Page_DEFAULT int64 = 1

func (p *PageRequest) GetPage() (v int64) {
	if !p.IsSetPage() {
		return PageRequest_Page_DEFAULT
	}
	return p.Page
}

var PageRequest_PageSize_DEFAULT int64 = 20

func (p *PageRequest) GetPageSize() (v int64) {
	if !p.IsSetPageSize() {
		return PageRequest_PageSize_DEFAULT
	}
	return p.PageSize
}
func (p *PageRequest) SetPage(val int64) {
	p.Page = val
}
func (p *PageRequest) SetPageSize(val int64) {
	p.PageSize = val
}

func (p *PageRequest) IsSetPage() bool {
	return p.Page != PageRequest_Page_DEFAULT
}

func (p *PageRequest) IsSetPageSize() bool {
	return p.PageSize != PageRequest_PageSize_DEFAULT
}

func (p *PageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageRequest(%+v)", *p)
}

var fieldIDToName_PageRequest = map[int16]string{
	1: "page",
	2: "page_size",
}

type PageResult_ struct {
	Total    int64 `thrift:"total,1" frugal:"1,default,i64" json:"total"`
	Page     int64 `thrift:"page,2" frugal:"2,default,i64" json:"page"`
	PageSize int64 `thrift:"page_size,3" frugal:"3,default,i64" json:"page_size"`
}

func NewPageResult_() *PageResult_ {
	return &PageResult_{}
}

func (p *PageResult_) InitDefault() {
}

func (p *PageResult_) GetTotal() (v int64) {
	return p.Total
}

func (p *PageResult_) GetPage() (v int64) {
	return p.Page
}

func (p *PageResult_) GetPageSize() (v int64) {
	return p.PageSize
}
func (p *PageResult_) SetTotal(val int64) {
	p.Total = val
}
func (p *PageResult_) SetPage(val int64) {
	p.Page = val
}
func (p *PageResult_) SetPageSize(val int64) {
	p.PageSize = val
}

func (p *PageResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageResult_(%+v)", *p)
}

var fieldIDToName_PageResult_ = map[int16]string{
	1: "total",
	2: "page",
	3: "page_size",
}

type Empty struct {
}

func NewEmpty() *Empty {
	return &Empty{}
}

func (p *Empty) InitDefault() {
}

func (p *Empty) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Empty(%+v)", *p)
}

var fieldIDToName_Empty = map[int16]string{}

type BizException struct {
	Code      ErrorCode `thrift:"code,1" frugal:"1,default,ErrorCode" json:"code"`
	Message   string    `thrift:"message,2" frugal:"2,default,string" json:"message"`
	RequestId *string   `thrift:"request_id,3,optional" frugal:"3,optional,string" json:"request_id,omitempty"`
}

func NewBizException() *BizException {
	return &BizException{}
}

func (p *BizException) InitDefault() {
}

func (p *BizException) GetCode() (v ErrorCode) {
	return p.Code
}

func (p *BizException) GetMessage() (v string) {
	return p.Message
}

var BizException_RequestId_DEFAULT string

func (p *BizException) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return BizException_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *BizException) SetCode(val ErrorCode) {
	p.Code = val
}
func (p *BizException) SetMessage(val string) {
	p.Message = val
}
func (p *BizException) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *BizException) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *BizException) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BizException(%+v)", *p)
}
func (p *BizException) Error() string {
	return p.String()
}

var fieldIDToName_BizException = map[int16]string{
	1: "code",
	2: "message",
	3: "request_id",
}
