// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package productclient

import (
	"context"

	"flash-mall/app/product/rpc/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductReq       = product.DeductReq
	Empty           = product.Empty
	RevertStockReq  = product.RevertStockReq
	RevertStockResp = product.RevertStockResp

	Product interface {
		// 扣减库存 (正向操作)
		Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*Empty, error)
		// 回滚库存 (补偿操作 - 用于事务失败时)
		DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*Empty, error)
		// 归还库存
		RevertStock(ctx context.Context, in *RevertStockReq, opts ...grpc.CallOption) (*RevertStockResp, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

// 扣减库存 (正向操作)
func (m *defaultProduct) Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.Deduct(ctx, in, opts...)
}

// 回滚库存 (补偿操作 - 用于事务失败时)
func (m *defaultProduct) DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DeductRollback(ctx, in, opts...)
}

// 归还库存
func (m *defaultProduct) RevertStock(ctx context.Context, in *RevertStockReq, opts ...grpc.CallOption) (*RevertStockResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.RevertStock(ctx, in, opts...)
}
