// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package productclient

import (
	"context"

	"flash-mall/app/product/rpc/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductReq          = product.DeductReq
	Empty              = product.Empty
	GetProductCardReq  = product.GetProductCardReq
	GetProductCardResp = product.GetProductCardResp
	ListProductsReq    = product.ListProductsReq
	ListProductsResp   = product.ListProductsResp
	RevertStockReq     = product.RevertStockReq
	RevertStockResp    = product.RevertStockResp

	Product interface {
		GetProductCard(ctx context.Context, in *GetProductCardReq, opts ...grpc.CallOption) (*GetProductCardResp, error)
		// 批量查询商品
		ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error)
		// 扣减库存（正向操作）
		Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*Empty, error)
		// 回滚库存（补偿操作，用于事务失败）
		DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*Empty, error)
		// 归还库存
		RevertStock(ctx context.Context, in *RevertStockReq, opts ...grpc.CallOption) (*RevertStockResp, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) GetProductCard(ctx context.Context, in *GetProductCardReq, opts ...grpc.CallOption) (*GetProductCardResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProductCard(ctx, in, opts...)
}

// 批量查询商品
func (m *defaultProduct) ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ListProducts(ctx, in, opts...)
}

// 扣减库存（正向操作）
func (m *defaultProduct) Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.Deduct(ctx, in, opts...)
}

// 回滚库存（补偿操作，用于事务失败）
func (m *defaultProduct) DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DeductRollback(ctx, in, opts...)
}

// 归还库存
func (m *defaultProduct) RevertStock(ctx context.Context, in *RevertStockReq, opts ...grpc.CallOption) (*RevertStockResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.RevertStock(ctx, in, opts...)
}
