// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package orderclient

import (
	"context"

	"flash-mall/app/order/rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PreDeductReq                  = order.PreDeductReq
	CreateOrderReq                = order.CreateOrderReq
	CreateOrderResp               = order.CreateOrderResp
	MarkOrderPaidReq              = order.MarkOrderPaidReq
	MarkOrderPaidResp             = order.MarkOrderPaidResp
	CreatePaymentReq              = order.CreatePaymentReq
	CreatePaymentResp             = order.CreatePaymentResp
	HandlePaymentNotificationReq  = order.HandlePaymentNotificationReq
	HandlePaymentNotificationResp = order.HandlePaymentNotificationResp
	GetOrderDetailReq             = order.GetOrderDetailReq
	GetOrderDetailResp            = order.GetOrderDetailResp
	RequestRefundReq              = order.RequestRefundReq
	RequestRefundResp             = order.RequestRefundResp
	AuditRefundReq                = order.AuditRefundReq
	AuditRefundResp               = order.AuditRefundResp
	OrderCommandMeta              = order.OrderCommandMeta
	CancelUserOrderReq            = order.CancelUserOrderReq
	CloseAdminOrderReq            = order.CloseAdminOrderReq
	ShipAdminOrderReq             = order.ShipAdminOrderReq
	ShipMerchantOrderReq          = order.ShipMerchantOrderReq
	ConfirmReceiptReq             = order.ConfirmReceiptReq
	OrderCommandResp              = order.OrderCommandResp
	Empty                         = order.Empty

	Order interface {
		// Redis 预扣库存（正向）
		PreDeduct(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error)
		// Redis 预扣回滚（补偿）
		PreDeductRollback(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error)
		// 创建订单（正向）
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		// 订单回滚/关闭（补偿）
		CreateOrderRollback(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*Empty, error)
		CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error)
		HandlePaymentNotification(ctx context.Context, in *HandlePaymentNotificationReq, opts ...grpc.CallOption) (*HandlePaymentNotificationResp, error)
		MarkOrderPaid(ctx context.Context, in *MarkOrderPaidReq, opts ...grpc.CallOption) (*MarkOrderPaidResp, error)
		GetOrderDetail(ctx context.Context, in *GetOrderDetailReq, opts ...grpc.CallOption) (*GetOrderDetailResp, error)
		RequestRefund(ctx context.Context, in *RequestRefundReq, opts ...grpc.CallOption) (*RequestRefundResp, error)
		AuditRefund(ctx context.Context, in *AuditRefundReq, opts ...grpc.CallOption) (*AuditRefundResp, error)
		CancelUserOrder(ctx context.Context, in *CancelUserOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
		CloseAdminOrder(ctx context.Context, in *CloseAdminOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
		ShipAdminOrder(ctx context.Context, in *ShipAdminOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
		ShipMerchantOrder(ctx context.Context, in *ShipMerchantOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
		ConfirmReceipt(ctx context.Context, in *ConfirmReceiptReq, opts ...grpc.CallOption) (*OrderCommandResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) PreDeduct(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.PreDeduct(ctx, in, opts...)
}

func (m *defaultOrder) PreDeductRollback(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.PreDeductRollback(ctx, in, opts...)
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) CreateOrderRollback(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrderRollback(ctx, in, opts...)
}

func (m *defaultOrder) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

func (m *defaultOrder) HandlePaymentNotification(ctx context.Context, in *HandlePaymentNotificationReq, opts ...grpc.CallOption) (*HandlePaymentNotificationResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.HandlePaymentNotification(ctx, in, opts...)
}

func (m *defaultOrder) MarkOrderPaid(ctx context.Context, in *MarkOrderPaidReq, opts ...grpc.CallOption) (*MarkOrderPaidResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.MarkOrderPaid(ctx, in, opts...)
}

func (m *defaultOrder) GetOrderDetail(ctx context.Context, in *GetOrderDetailReq, opts ...grpc.CallOption) (*GetOrderDetailResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrderDetail(ctx, in, opts...)
}

func (m *defaultOrder) RequestRefund(ctx context.Context, in *RequestRefundReq, opts ...grpc.CallOption) (*RequestRefundResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.RequestRefund(ctx, in, opts...)
}

func (m *defaultOrder) AuditRefund(ctx context.Context, in *AuditRefundReq, opts ...grpc.CallOption) (*AuditRefundResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.AuditRefund(ctx, in, opts...)
}

func (m *defaultOrder) CancelUserOrder(ctx context.Context, in *CancelUserOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CancelUserOrder(ctx, in, opts...)
}

func (m *defaultOrder) CloseAdminOrder(ctx context.Context, in *CloseAdminOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CloseAdminOrder(ctx, in, opts...)
}

func (m *defaultOrder) ShipAdminOrder(ctx context.Context, in *ShipAdminOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.ShipAdminOrder(ctx, in, opts...)
}

func (m *defaultOrder) ShipMerchantOrder(ctx context.Context, in *ShipMerchantOrderReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.ShipMerchantOrder(ctx, in, opts...)
}

func (m *defaultOrder) ConfirmReceipt(ctx context.Context, in *ConfirmReceiptReq, opts ...grpc.CallOption) (*OrderCommandResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.ConfirmReceipt(ctx, in, opts...)
}
