// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package orderclient

import (
	"context"

	"flash-mall/app/order/rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PreDeductReq   = order.PreDeductReq
	CreateOrderReq = order.CreateOrderReq
	Empty          = order.Empty

	Order interface {
		// Redis 预扣库存（正向）
		PreDeduct(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error)
		// Redis 预扣回滚（补偿）
		PreDeductRollback(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error)
		// 创建订单（正向）
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*Empty, error)
		// 订单回滚/关闭（补偿）
		CreateOrderRollback(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) PreDeduct(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.PreDeduct(ctx, in, opts...)
}

func (m *defaultOrder) PreDeductRollback(ctx context.Context, in *PreDeductReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.PreDeductRollback(ctx, in, opts...)
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) CreateOrderRollback(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*Empty, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrderRollback(ctx, in, opts...)
}
