global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: hertz-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["hertz-gateway:8889"]
  - job_name: order-rpc
    metrics_path: /metrics
    static_configs:
      - targets: ["order-rpc:9091"]
  - job_name: product-rpc
    metrics_path: /metrics
    static_configs:
      - targets: ["product-rpc:9092"]
  - job_name: inventory-kitex
    metrics_path: /metrics
    static_configs:
      - targets: ["inventory-kitex:9093"]
  - job_name: dtm
    metrics_path: /api/metrics
    static_configs:
      - targets: ["dtm:36789"]
