// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"flash-mall/app/order/rpc/internal/logic"
	"flash-mall/app/order/rpc/internal/svc"
	"flash-mall/app/order/rpc/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// Redis 预扣库存（正向）
func (s *OrderServer) PreDeduct(ctx context.Context, in *order.PreDeductReq) (*order.Empty, error) {
	l := logic.NewPreDeductLogic(ctx, s.svcCtx)
	return l.PreDeduct(in)
}

// Redis 预扣回滚（补偿）
func (s *OrderServer) PreDeductRollback(ctx context.Context, in *order.PreDeductReq) (*order.Empty, error) {
	l := logic.NewPreDeductRollbackLogic(ctx, s.svcCtx)
	return l.PreDeductRollback(in)
}

// 创建订单（正向）
func (s *OrderServer) CreateOrder(ctx context.Context, in *order.CreateOrderReq) (*order.CreateOrderResp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 订单回滚/关闭（补偿）
func (s *OrderServer) CreateOrderRollback(ctx context.Context, in *order.CreateOrderReq) (*order.Empty, error) {
	l := logic.NewCreateOrderRollbackLogic(ctx, s.svcCtx)
	return l.CreateOrderRollback(in)
}

func (s *OrderServer) MarkOrderPaid(ctx context.Context, in *order.MarkOrderPaidReq) (*order.MarkOrderPaidResp, error) {
	l := logic.NewMarkOrderPaidLogic(ctx, s.svcCtx)
	return l.MarkPaid(in)
}

func (s *OrderServer) GetOrderDetail(ctx context.Context, in *order.GetOrderDetailReq) (*order.GetOrderDetailResp, error) {
	l := logic.NewGetOrderDetailLogic(ctx, s.svcCtx)
	return l.GetOrderDetail(in)
}

func (s *OrderServer) RequestRefund(ctx context.Context, in *order.RequestRefundReq) (*order.RequestRefundResp, error) {
	l := logic.NewRequestRefundLogic(ctx, s.svcCtx)
	return l.RequestRefund(in)
}

func (s *OrderServer) AuditRefund(ctx context.Context, in *order.AuditRefundReq) (*order.AuditRefundResp, error) {
	l := logic.NewAuditRefundLogic(ctx, s.svcCtx)
	return l.AuditRefund(in)
}

func (s *OrderServer) CancelUserOrder(ctx context.Context, in *order.CancelUserOrderReq) (*order.OrderCommandResp, error) {
	l := logic.NewCancelUserOrderLogic(ctx, s.svcCtx)
	return l.CancelUserOrder(in)
}

func (s *OrderServer) CloseAdminOrder(ctx context.Context, in *order.CloseAdminOrderReq) (*order.OrderCommandResp, error) {
	l := logic.NewCloseAdminOrderLogic(ctx, s.svcCtx)
	return l.CloseAdminOrder(in)
}

func (s *OrderServer) ShipAdminOrder(ctx context.Context, in *order.ShipAdminOrderReq) (*order.OrderCommandResp, error) {
	l := logic.NewShipAdminOrderLogic(ctx, s.svcCtx)
	return l.ShipAdminOrder(in)
}

func (s *OrderServer) ShipMerchantOrder(ctx context.Context, in *order.ShipMerchantOrderReq) (*order.OrderCommandResp, error) {
	l := logic.NewShipMerchantOrderLogic(ctx, s.svcCtx)
	return l.ShipMerchantOrder(in)
}

func (s *OrderServer) ConfirmReceipt(ctx context.Context, in *order.ConfirmReceiptReq) (*order.OrderCommandResp, error) {
	l := logic.NewConfirmReceiptLogic(ctx, s.svcCtx)
	return l.ConfirmReceipt(in)
}
