// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"flash-mall/app/order/rpc/internal/logic"
	"flash-mall/app/order/rpc/internal/svc"
	"flash-mall/app/order/rpc/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// Redis 预扣库存（正向）
func (s *OrderServer) PreDeduct(ctx context.Context, in *order.PreDeductReq) (*order.Empty, error) {
	l := logic.NewPreDeductLogic(ctx, s.svcCtx)
	return l.PreDeduct(in)
}

// Redis 预扣回滚（补偿）
func (s *OrderServer) PreDeductRollback(ctx context.Context, in *order.PreDeductReq) (*order.Empty, error) {
	l := logic.NewPreDeductRollbackLogic(ctx, s.svcCtx)
	return l.PreDeductRollback(in)
}

// 创建订单（正向）
func (s *OrderServer) CreateOrder(ctx context.Context, in *order.CreateOrderReq) (*order.Empty, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 订单回滚/关闭（补偿）
func (s *OrderServer) CreateOrderRollback(ctx context.Context, in *order.CreateOrderReq) (*order.Empty, error) {
	l := logic.NewCreateOrderRollbackLogic(ctx, s.svcCtx)
	return l.CreateOrderRollback(in)
}
