// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateOrderReq struct {
	// CHG 2026-02-07: 变更=新增 request_id; 之前=无幂等键; 原因=重复请求返回同一订单避免双下单。
	RequestId string `json:"request_id"`
	UserId    int64  `json:"user_id"`
	ProductId int64  `json:"product_id"`
	Amount    int64  `json:"amount"` // 购买数量
}

type CreateOrderResp struct {
	OrderId string `json:"order_id"`
}

type LoginReq struct {
	UserId   int64  `json:"user_id"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"access_token"`
	TokenType   string `json:"token_type"`
	ExpiresAt   int64  `json:"expires_at"`
}

type DependencyStatus struct {
	Name   string `json:"name"`
	Ok     bool   `json:"ok"`
	Detail string `json:"detail"`
}

type SystemHealthResp struct {
	Overall      bool               `json:"overall"`
	ServerTime   int64              `json:"server_time"`
	Dependencies []DependencyStatus `json:"dependencies"`
}
